// AUTO-GENERATED BY FLUXFAST.
// DO NOT EDIT MANUALLY.
// Schema: fluxfast-schema/1
// Producer: 0.7.0
// Fingerprint: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

import type {} from "@fluxfast/core";

export const resourceKeys = {
  rooms: "rooms",
} as const;

export interface LegacyRoom {
  id: number;
  name: string;
}

export type RoomsResource = LegacyRoom[];

export interface GeneratedFluxResourceMap {
  rooms: RoomsResource;
}

declare module "@fluxfast/core" {
  interface FluxResourceMap {
    rooms: RoomsResource;
  }
}
