import fs from "node:fs";
import path from "node:path";

export interface GenerateOptions {
  pagesDir?: string;
  outputFile?: string;
}

const PAGE_EXTENSION = /\.(tsx|jsx)$/;
const IGNORED_PAGE = /\.(test|spec|stories)\.(tsx|jsx)$/;

export function generatePagesRegistry(options: GenerateOptions = {}): void {
  const rootDir = process.cwd();
  const pagesDir = path.resolve(rootDir, options.pagesDir ?? "src/flux-pages");
  const outputFile = path.resolve(
    rootDir,
    options.outputFile ?? "src/.fluxfast/pages.generated.ts"
  );

  fs.mkdirSync(pagesDir, { recursive: true });
  fs.mkdirSync(path.dirname(outputFile), { recursive: true });

  const foundFiles: string[] = [];
  const scanDir = (dir: string, base = ""): void => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const relative = base ? `${base}/${entry.name}` : entry.name;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        scanDir(fullPath, relative);
      } else if (
        entry.isFile() &&
        PAGE_EXTENSION.test(entry.name) &&
        !IGNORED_PAGE.test(entry.name) &&
        !entry.name.startsWith("_")
      ) {
        foundFiles.push(relative);
      }
    }
  };

  scanDir(pagesDir);
  foundFiles.sort();

  const outputDir = path.dirname(outputFile);
  const entries = foundFiles.map(file => {
    const identifier = file.replace(PAGE_EXTENSION, "");
    const relativeImport = path
      .relative(outputDir, path.join(pagesDir, file))
      .replace(PAGE_EXTENSION, "")
      .replace(/\\/g, "/");
    const importPath = relativeImport.startsWith(".")
      ? relativeImport
      : `./${relativeImport}`;
    return `  ${JSON.stringify(identifier)}: { load: () => import(${JSON.stringify(importPath)}) },`;
  });

  const content = `// AUTO-GENERATED BY FLUXFAST.\n// DO NOT EDIT MANUALLY.\n"use client";\n\nimport React from "react";\nimport { FluxRoot } from "@fluxfast/next";\nimport type { ComponentRegistry, FluxApplicationProps } from "@fluxfast/next";\n\nexport const fluxPages: ComponentRegistry = {\n${entries.join("\n")}\n};\n\nexport function FluxApplication(props: FluxApplicationProps) {\n  return React.createElement(FluxRoot, { ...props, registry: fluxPages });\n}\n\nexport default fluxPages;\n`;

  fs.writeFileSync(outputFile, content, "utf8");
  console.log(
    `[fluxfast] Generated component registry with ${foundFiles.length} pages at ${outputFile}`
  );
}
