import fs from "node:fs";
import path from "node:path";
import {
  checkFluxFastProject as checkSharedProject,
  generateFluxFastProject as generateSharedProject,
  generatePagesRegistry as generateSharedRegistry,
} from "@fluxfast/codegen";
import type { ValidatorCompilationDiagnostic } from "@fluxfast/codegen";

export interface GenerateOptions {
  pagesDir?: string;
  outputFile?: string;
  log?: boolean;
}

export interface PagesRegistrySnapshot {
  content: string;
  files: string[];
  identifiers: string[];
  outputFile: string;
  pagesDir: string;
}

export interface FluxFastGenerationOptions extends GenerateOptions {
  generatedDir?: string;
  /** Manifest content to validate and persist at `schemaFile`. */
  schemaContent?: string;
  schemaFile?: string;
}

export interface FluxFastGenerationResult {
  generatedFiles: string[];
  generatedValidators: readonly string[];
  registryPath: string;
  schemaFile?: string;
  validatorDiagnostics: readonly ValidatorCompilationDiagnostic[];
}

export interface FluxFastGenerationCheckResult {
  checkedFiles: string[];
  current: boolean;
  generatedValidators: readonly string[];
  registryPath: string;
  schemaFile?: string;
  staleFiles: string[];
  validatorDiagnostics: readonly ValidatorCompilationDiagnostic[];
}

const PAGE_EXTENSION = /\.(tsx|jsx)$/;
const IGNORED_PAGE = /\.(test|spec|stories)\.(tsx|jsx)$/;
const SAFE_PAGE_FILE =
  /^[A-Za-z0-9_.@()\[\]-]+(?:\/[A-Za-z0-9_.@()\[\]-]+)*\.(?:tsx|jsx)$/;

function assertSafePageFile(file: string): void {
  const hasTraversalSegment = file
    .split("/")
    .some(segment => segment === "." || segment === "..");
  if (!SAFE_PAGE_FILE.test(file) || hasTraversalSegment) {
    throw new TypeError(
      `[fluxfast] Page path contains unsupported characters: ${JSON.stringify(file)}`
    );
  }
}

/** Render the deterministic registry in memory without modifying the project. */
export function createPagesRegistrySnapshot(
  options: GenerateOptions = {}
): PagesRegistrySnapshot {
  const rootDir = process.cwd();
  const pagesDir = path.resolve(rootDir, options.pagesDir ?? "src/flux-pages");
  const outputFile = path.resolve(
    rootDir,
    options.outputFile ?? "src/.fluxfast/pages.generated.ts"
  );

  const foundFiles: string[] = [];
  const scanDir = (dir: string, base = ""): void => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const relative = base ? `${base}/${entry.name}` : entry.name;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        scanDir(fullPath, relative);
      } else if (
        entry.isFile() &&
        PAGE_EXTENSION.test(entry.name) &&
        !IGNORED_PAGE.test(entry.name) &&
        !entry.name.startsWith("_")
      ) {
        assertSafePageFile(relative);
        foundFiles.push(relative);
      }
    }
  };

  if (fs.existsSync(pagesDir)) {
    scanDir(pagesDir);
  }
  foundFiles.sort();

  const identifiers = foundFiles.map(file => file.replace(PAGE_EXTENSION, ""));
  const identifierFiles = new Map<string, string>();
  for (let index = 0; index < identifiers.length; index += 1) {
    const identifier = identifiers[index];
    const file = foundFiles[index];
    const previous = identifierFiles.get(identifier);
    if (previous) {
      throw new TypeError(
        `[fluxfast] Duplicate FluxFast page identifier ${JSON.stringify(identifier)} from ${JSON.stringify(previous)} and ${JSON.stringify(file)}`
      );
    }
    identifierFiles.set(identifier, file);
  }

  const outputDir = path.dirname(outputFile);
  const entries = foundFiles.map((file, index) => {
    const identifier = identifiers[index];
    const relativeImport = path
      .relative(outputDir, path.join(pagesDir, file))
      .replace(PAGE_EXTENSION, "")
      .replace(/\\/g, "/");
    const importPath = relativeImport.startsWith(".")
      ? relativeImport
      : `./${relativeImport}`;
    return `  ${JSON.stringify(identifier)}: { load: () => import(${JSON.stringify(importPath)}) },`;
  });

  const content = `// AUTO-GENERATED BY FLUXFAST.\n// DO NOT EDIT MANUALLY.\n"use client";\n\nimport React from "react";\nimport { FluxRoot } from "@fluxfast/next";\nimport type { ComponentRegistry, FluxApplicationProps } from "@fluxfast/next";\n\nexport const fluxPages: ComponentRegistry = {\n${entries.join("\n")}\n};\n\nexport function FluxApplication(props: FluxApplicationProps) {\n  return React.createElement(FluxRoot, { ...props, registry: fluxPages });\n}\n\nexport default fluxPages;\n`;

  return { content, files: foundFiles, identifiers, outputFile, pagesDir };
}

export function generatePagesRegistry(options: GenerateOptions = {}): void {
  generateSharedRegistry(createPagesRegistrySnapshot(options), { log: options.log });
}

/** Generate through framework-neutral Codegen with the existing Next registry. */
export function generateFluxFastProject(
  options: FluxFastGenerationOptions = {}
): FluxFastGenerationResult {
  return generateSharedProject({ ...options, registry: createPagesRegistrySnapshot(options) });
}

/** Check through Codegen without creating or modifying files. */
export function checkFluxFastProject(
  options: FluxFastGenerationOptions = {}
): FluxFastGenerationCheckResult {
  return checkSharedProject({ ...options, registry: createPagesRegistrySnapshot(options) });
}
