import {
  type FluxFastMutationRouteSchema,
  type FluxFastRouteParameterSchema,
  type JsonSchema,
  validateFluxFastSchemaManifest
} from "./schema-manifest";
import {
  compileInlineJsonSchemaType,
  mutationBodyTypeName,
  mutationOperationIdentifier,
  SchemaCompilationError
} from "./schema-compiler";

interface TypedMutationRouteSchema extends FluxFastMutationRouteSchema {
  body: JsonSchema;
}

interface MutationOperation {
  bodyTypeName: string;
  identifier: string;
  mutation: TypedMutationRouteSchema;
  sourceIndex: number;
}

interface MutationPlaceholder {
  name: string;
  token: string;
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function propertyName(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)
    ? value
    : JSON.stringify(value);
}

function fail(path: string, reason: string): never {
  throw new SchemaCompilationError(path, reason);
}

function placeholders(path: string): MutationPlaceholder[] {
  const result: MutationPlaceholder[] = [];
  const pattern = /\{([^{}:]+)(?::[^{}]+)?\}/g;
  for (const match of path.matchAll(pattern)) {
    result.push({ name: match[1], token: match[0] });
  }
  return result;
}

function sortParameters(
  parameters: FluxFastRouteParameterSchema[]
): FluxFastRouteParameterSchema[] {
  return [...parameters].sort((left, right) =>
    compareText(left.location, right.location) ||
    compareText(left.name, right.name)
  );
}

class MutationCompiler {
  constructor(
    private readonly manifest: ReturnType<typeof validateFluxFastSchemaManifest>
  ) {}

  compile(): string {
    const operations = this.collectOperations();
    const header = [
      "// AUTO-GENERATED BY FLUXFAST.",
      "// DO NOT EDIT MANUALLY.",
      `// Schema: ${this.manifest.schema}`,
      `// Producer: ${this.manifest.producer}`,
      `// Fingerprint: ${this.manifest.fingerprint}`
    ];
    if (operations.length === 0) {
      return `${header.join("\n")}\n\nexport const mutations = {} as const;\n`;
    }

    const helper = `function appendFluxMutationQuery(
  search: URLSearchParams,
  key: string,
  value: unknown
): void {
  if (value === undefined || value === null) return;
  if (Array.isArray(value)) {
    for (const item of value) appendFluxMutationQuery(search, key, item);
    return;
  }
  search.append(key, String(value));
}`;
    const entries = operations.map(operation => this.renderOperation(operation));
    const bodyTypes = [...new Set(operations.map(operation => operation.bodyTypeName))]
      .sort(compareText);
    const imports = [
      "import type { FluxRouter, MutationEnvelope } from \"@fluxfast/core\";",
      `import type { ${bodyTypes.join(", ")} } from \"./types.generated\";`
    ].join("\n");
    return `${header.join("\n")}\n\n${imports}\n\n${helper}\n\nexport const mutations = {\n${entries.join("\n")}\n} as const;\n`;
  }

  private collectOperations(): MutationOperation[] {
    const mutations = this.manifest.mutations
      .map((mutation, sourceIndex) => ({ mutation, sourceIndex }))
      .filter(
        (entry): entry is {
          mutation: TypedMutationRouteSchema;
          sourceIndex: number;
        } => entry.mutation.body !== undefined && entry.mutation.body !== null
      )
      .sort((left, right) =>
        compareText(left.mutation.name, right.mutation.name) ||
        compareText(left.mutation.path, right.mutation.path) ||
        compareText(left.mutation.method, right.mutation.method)
      );
    const groupSizes = new Map<string, number>();
    for (const { mutation } of mutations) {
      const key = `${mutation.name}\u0000${mutation.path}`;
      groupSizes.set(key, (groupSizes.get(key) ?? 0) + 1);
    }

    const identifiers = new Map<string, TypedMutationRouteSchema>();
    return mutations.map(({ mutation, sourceIndex }) => {
      const groupKey = `${mutation.name}\u0000${mutation.path}`;
      const groupSize = groupSizes.get(groupKey)!;
      const identifier = mutationOperationIdentifier(
        mutation.name,
        mutation.method,
        groupSize
      );
      const bodyTypeName = mutationBodyTypeName(
        mutation.name,
        mutation.method,
        groupSize
      );
      const existing = identifiers.get(identifier);
      if (existing) {
        fail(
          `$.mutations[${sourceIndex}].name`,
          `mutation ${JSON.stringify(mutation.name)} (${mutation.method} ${mutation.path}) collides with ${JSON.stringify(
            existing.name
          )} (${existing.method} ${existing.path}) as TypeScript identifier mutations.${identifier}. Give the FluxFast mutation route an explicit unique name.`
        );
      }
      identifiers.set(identifier, mutation);
      this.validatePlaceholders(mutation, sourceIndex);
      return { bodyTypeName, identifier, mutation, sourceIndex };
    });
  }

  private validatePlaceholders(
    mutation: FluxFastMutationRouteSchema,
    sourceIndex: number
  ): void {
    const mutationPath = `$.mutations[${sourceIndex}]`;
    const pathParameters = mutation.parameters.filter(
      parameter => parameter.location === "path"
    );
    const routePlaceholders = placeholders(mutation.path);
    for (const placeholder of routePlaceholders) {
      const matches = pathParameters.filter(
        parameter => parameter.name === placeholder.name
      );
      if (matches.length !== 1) {
        fail(
          `${mutationPath}.path`,
          `placeholder ${JSON.stringify(placeholder.name)} must have exactly one path parameter`
        );
      }
    }
    for (const parameter of pathParameters) {
      const matches = routePlaceholders.filter(
        placeholder => placeholder.name === parameter.name
      );
      if (matches.length !== 1) {
        fail(
          `${mutationPath}.parameters`,
          `path parameter ${JSON.stringify(parameter.name)} must appear exactly once in the mutation path`
        );
      }
    }
  }

  private renderOperation(operation: MutationOperation): string {
    const { identifier, mutation, sourceIndex } = operation;
    const mutationPath = `$.mutations[${sourceIndex}]`;
    const parameters = sortParameters(mutation.parameters);
    const pathParameters = parameters.filter(
      parameter => parameter.location === "path"
    );
    const queryParameters = parameters.filter(
      parameter => parameter.location === "query"
    );
    const inputType = this.renderInputType(
      mutation,
      pathParameters,
      queryParameters,
      mutationPath,
      operation.bodyTypeName
    );
    const body = [`    let path = ${JSON.stringify(mutation.path)};`];
    const routePlaceholders = placeholders(mutation.path);
    for (const parameter of pathParameters) {
      const placeholder = routePlaceholders.find(
        candidate => candidate.name === parameter.name
      )!;
      body.push(
        `    path = path.replace(${JSON.stringify(placeholder.token)}, encodeURIComponent(String(input.params[${JSON.stringify(parameter.name)}])));`
      );
    }
    if (queryParameters.length > 0) {
      body.push("    const search = new URLSearchParams();");
      for (const parameter of queryParameters) {
        body.push(
          `    appendFluxMutationQuery(search, ${JSON.stringify(parameter.name)}, input.query?.[${JSON.stringify(parameter.name)}]);`
        );
      }
      body.push("    const query = search.toString();");
      body.push('    if (query) path = `${path}?${query}`;');
    }
    body.push(
      `    return router.mutate(path, input.body, { method: ${JSON.stringify(mutation.method)} });`
    );
    return `  ${identifier}: (\n    router: FluxRouter,\n    input: ${inputType}\n  ): Promise<MutationEnvelope> => {\n${body.join("\n")}\n  },`;
  }

  private renderInputType(
    mutation: TypedMutationRouteSchema,
    pathParameters: FluxFastRouteParameterSchema[],
    queryParameters: FluxFastRouteParameterSchema[],
    mutationPath: string,
    bodyTypeName: string
  ): string {
    const entries: string[] = [];
    if (pathParameters.length > 0) {
      const parameterEntries = pathParameters.map(parameter =>
        `    ${propertyName(parameter.name)}: ${compileInlineJsonSchemaType(
          parameter.schema,
          `${mutationPath}.parameters[${mutation.parameters.indexOf(parameter)}].schema`
        )};`
      );
      entries.push(`  params: {\n${parameterEntries.join("\n")}\n  };`);
    }
    if (queryParameters.length > 0) {
      const parameterEntries = queryParameters.map(parameter =>
        `    ${propertyName(parameter.name)}${parameter.required ? "" : "?"}: ${compileInlineJsonSchemaType(
          parameter.schema,
          `${mutationPath}.parameters[${mutation.parameters.indexOf(parameter)}].schema`
        )};`
      );
      const queryRequired = queryParameters.some(
        parameter => parameter.required
      );
      entries.push(
        `  query${queryRequired ? "" : "?"}: {\n${parameterEntries.join("\n")}\n  };`
      );
    }
    entries.push(`  body: ${bodyTypeName};`);
    return `{\n${entries.join("\n")}\n}`;
  }
}

/** Compile typed JSON mutations into deterministic FluxRouter helpers. */
export function compileFluxFastMutations(value: unknown): string {
  const manifest = validateFluxFastSchemaManifest(value);
  return new MutationCompiler(manifest).compile();
}
