import {
  type FluxFastPageRouteSchema,
  type FluxFastRouteParameterSchema,
  validateFluxFastSchemaManifest
} from "./schema-manifest";
import {
  camelIdentifier,
  compileInlineJsonSchemaType,
  SchemaCompilationError
} from "./schema-compiler";

interface RoutePlaceholder {
  name: string;
  token: string;
}

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function propertyName(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)
    ? value
    : JSON.stringify(value);
}

function fail(path: string, reason: string): never {
  throw new SchemaCompilationError(path, reason);
}

function placeholders(path: string): RoutePlaceholder[] {
  const result: RoutePlaceholder[] = [];
  const pattern = /\{([^{}:]+)(?::[^{}]+)?\}/g;
  for (const match of path.matchAll(pattern)) {
    result.push({ name: match[1], token: match[0] });
  }
  return result;
}

function sortParameters(
  parameters: FluxFastRouteParameterSchema[]
): FluxFastRouteParameterSchema[] {
  return [...parameters].sort((left, right) =>
    compareText(left.location, right.location) ||
    compareText(left.name, right.name)
  );
}

class PageRouteCompiler {
  private readonly routeNames = new Map<string, string>();

  constructor(
    private readonly manifest: ReturnType<typeof validateFluxFastSchemaManifest>
  ) {}

  compile(): string {
    const pages = [...this.manifest.pages].sort((left, right) =>
      compareText(left.name, right.name) || compareText(left.path, right.path)
    );
    this.validateRoutes(pages);

    const header = [
      "// AUTO-GENERATED BY FLUXFAST.",
      "// DO NOT EDIT MANUALLY.",
      `// Schema: ${this.manifest.schema}`,
      `// Producer: ${this.manifest.producer}`,
      `// Fingerprint: ${this.manifest.fingerprint}`
    ];
    if (pages.length === 0) {
      return `${header.join("\n")}\n\nexport const routes = {} as const;\n`;
    }

    const helper = `function appendFluxRouteQuery(
  search: URLSearchParams,
  key: string,
  value: unknown
): void {
  if (value === undefined || value === null) return;
  if (Array.isArray(value)) {
    for (const item of value) appendFluxRouteQuery(search, key, item);
    return;
  }
  search.append(key, String(value));
}`;
    const entries = pages.map(page =>
      this.renderRoute(
        page,
        `$.pages[${this.manifest.pages.indexOf(page)}]`
      )
    );
    return `${header.join("\n")}\n\n${helper}\n\nexport const routes = {\n${entries.join("\n")}\n} as const;\n`;
  }

  private validateRoutes(pages: FluxFastPageRouteSchema[]): void {
    for (const page of pages) {
      const pagePath = `$.pages[${this.manifest.pages.indexOf(page)}]`;
      const identifier = camelIdentifier(page.name);
      const existing = this.routeNames.get(identifier);
      if (existing !== undefined) {
        fail(
          `${pagePath}.name`,
          `page route ${JSON.stringify(page.name)} collides with ${JSON.stringify(
            existing
          )} as TypeScript identifier routes.${identifier}. Give the FluxFast page route an explicit unique name.`
        );
      }
      this.routeNames.set(identifier, page.name);

      const pathParameters = page.parameters.filter(
        parameter => parameter.location === "path"
      );
      const routePlaceholders = placeholders(page.path);
      for (const placeholder of routePlaceholders) {
        const matches = pathParameters.filter(
          parameter => parameter.name === placeholder.name
        );
        if (matches.length !== 1) {
          fail(
            `${pagePath}.path`,
            `placeholder ${JSON.stringify(placeholder.name)} must have exactly one path parameter`
          );
        }
      }
      for (const parameter of pathParameters) {
        const matches = routePlaceholders.filter(
          placeholder => placeholder.name === parameter.name
        );
        if (matches.length !== 1) {
          fail(
            `${pagePath}.parameters`,
            `path parameter ${JSON.stringify(parameter.name)} must appear exactly once in the route path`
          );
        }
      }
    }
  }

  private renderRoute(page: FluxFastPageRouteSchema, pagePath: string): string {
    const parameters = sortParameters(page.parameters);
    const pathParameters = parameters.filter(
      parameter => parameter.location === "path"
    );
    const queryParameters = parameters.filter(
      parameter => parameter.location === "query"
    );
    const inputType = this.renderInputType(
      pathParameters,
      queryParameters,
      page.parameters,
      pagePath
    );
    const inputRequired =
      pathParameters.length > 0 ||
      queryParameters.some(parameter => parameter.required);
    const hasInput = pathParameters.length > 0 || queryParameters.length > 0;
    const signature = !hasInput
      ? "()"
      : inputRequired
        ? `(input: ${inputType})`
        : `(input: ${inputType} = {})`;

    const body = [`    let path = ${JSON.stringify(page.path)};`];
    const routePlaceholders = placeholders(page.path);
    for (const parameter of pathParameters) {
      const placeholder = routePlaceholders.find(
        candidate => candidate.name === parameter.name
      )!;
      body.push(
        `    path = path.replace(${JSON.stringify(placeholder.token)}, encodeURIComponent(String(input[${JSON.stringify(parameter.name)}])));`
      );
    }
    if (queryParameters.length > 0) {
      body.push("    const search = new URLSearchParams();");
      for (const parameter of queryParameters) {
        body.push(
          `    appendFluxRouteQuery(search, ${JSON.stringify(parameter.name)}, input.query?.[${JSON.stringify(parameter.name)}]);`
        );
      }
      body.push("    const query = search.toString();");
      body.push('    return query ? `${path}?${query}` : path;');
    } else {
      body.push("    return path;");
    }

    return `  ${camelIdentifier(page.name)}: ${signature}: string => {\n${body.join("\n")}\n  },`;
  }

  private renderInputType(
    pathParameters: FluxFastRouteParameterSchema[],
    queryParameters: FluxFastRouteParameterSchema[],
    sourceParameters: FluxFastRouteParameterSchema[],
    pagePath: string
  ): string {
    const entries = pathParameters.map(parameter =>
      `  ${propertyName(parameter.name)}: ${compileInlineJsonSchemaType(
        parameter.schema,
        `${pagePath}.parameters[${sourceParameters.indexOf(parameter)}].schema`
      )};`
    );
    if (queryParameters.length > 0) {
      const queryEntries = queryParameters.map(parameter =>
        `    ${propertyName(parameter.name)}${parameter.required ? "" : "?"}: ${compileInlineJsonSchemaType(
          parameter.schema,
          `${pagePath}.parameters[${sourceParameters.indexOf(parameter)}].schema`
        )};`
      );
      const queryRequired = queryParameters.some(
        parameter => parameter.required
      );
      entries.push(
        `  query${queryRequired ? "" : "?"}: {\n${queryEntries.join("\n")}\n  };`
      );
    }
    return `{\n${entries.join("\n")}\n}`;
  }
}

/** Compile authoritative page metadata into deterministic typed URL builders. */
export function compileFluxFastPageRoutes(value: unknown): string {
  const manifest = validateFluxFastSchemaManifest(value);
  return new PageRouteCompiler(manifest).compile();
}
