import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  desiredCatchAllPath,
  desiredHealthRoutePath,
  desiredHomePagePath,
  desiredTransportRoutePath,
  relativeImport,
  renderCatchAll,
  renderFluxConfig,
  renderHealthRoute,
  renderStarterPage,
  renderTransportRoute,
} from "../../src/cli/files";
import { detectFluxProject } from "../../src/cli/project";
import { createTestProject, writeTestFile } from "./helpers";

describe("FluxFast scaffold templates", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "fluxfast-files-test-"));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("renders minimal TypeScript src templates using a valid @ alias", () => {
    createTestProject(tmpDir);
    writeTestFile(
      tmpDir,
      "tsconfig.json",
      '{"compilerOptions":{"paths":{"@/*":["./src/*"]}}}\n'
    );
    const project = detectFluxProject(tmpDir);

    expect(project.usesAtAlias).toBe(true);
    expect(desiredCatchAllPath(project)).toBe(
      path.join(tmpDir, "src/app/(flux)/[[...flux]]/page.tsx")
    );
    expect(desiredHomePagePath(project)).toBe(
      path.join(tmpDir, "src/flux-pages/home/index.tsx")
    );
    expect(desiredHealthRoutePath(project)).toBe(
      path.join(tmpDir, "src/app/%5Ffluxfast/[probe]/route.ts")
    );
    expect(desiredTransportRoutePath(project)).toBe(
      path.join(
        tmpDir,
        "src/app/%5Ffluxfast/transport/[[...path]]/route.ts"
      )
    );
    expect(renderCatchAll(project)).toBe(
      '// GENERATED BY FLUXFAST.\n// Run `fluxfast init --force` to repair this file.\n\nimport { createFluxNextPage } from "@fluxfast/next/server";\nimport { fluxConfig } from "@/fluxfast.config";\n\nexport const dynamic = "force-dynamic";\n\nexport default createFluxNextPage(fluxConfig);\n'
    );
    expect(renderFluxConfig(project)).toBe(
      'import { defineFluxConfig } from "@fluxfast/next";\nimport { FluxApplication } from "@/.fluxfast/pages.generated";\n\nexport const fluxConfig = defineFluxConfig({\n  application: FluxApplication,\n});\n'
    );
    expect(renderHealthRoute()).toBe(
      '// GENERATED BY FLUXFAST.\n// Run `fluxfast init --force` to repair this file.\n\nimport { createFluxHealthHandler } from "@fluxfast/next/server";\n\nexport const dynamic = "force-dynamic";\nexport const GET = createFluxHealthHandler();\n'
    );
    expect(renderTransportRoute()).toContain("createFluxTransportHandler");
    expect(renderTransportRoute()).toContain("export const POST = transport");
  });

  it("renders JavaScript root templates with portable relative imports", () => {
    createTestProject(tmpDir, { language: "javascript", layout: "root" });
    const project = detectFluxProject(tmpDir);

    expect(project.usesAtAlias).toBe(false);
    expect(desiredCatchAllPath(project)).toBe(
      path.join(tmpDir, "app/(flux)/[[...flux]]/page.jsx")
    );
    expect(desiredHealthRoutePath(project)).toBe(
      path.join(tmpDir, "app/%5Ffluxfast/[probe]/route.js")
    );
    expect(desiredTransportRoutePath(project)).toBe(
      path.join(tmpDir, "app/%5Ffluxfast/transport/[[...path]]/route.js")
    );
    expect(renderCatchAll(project)).toContain(
      'import { fluxConfig } from "../../../fluxfast.config";'
    );
    expect(renderFluxConfig(project)).toContain(
      'import { FluxApplication } from "./.fluxfast/pages.generated";'
    );
  });

  it("normalizes Windows import separators", () => {
    expect(
      relativeImport(
        "C:\\project\\src\\app\\(flux)\\[[...flux]]\\page.tsx",
        "C:\\project\\src\\fluxfast.config.ts",
        path.win32
      )
    ).toBe("../../../fluxfast.config");
  });

  it("renders a generic starter without backend resource assumptions", () => {
    const starter = renderStarterPage();

    expect(starter).toContain('"use client";');
    expect(starter).toContain("Your FluxFast frontend is ready.");
    expect(starter).not.toContain("useResource");
  });
});
