import path from "node:path";
import type { DetectedPackage, FluxProjectInfo } from "./types.js";

export const FLUXFAST_AGENT_KNOWLEDGE_MARKER =
  "<!-- GENERATED BY FLUXFAST. Run `npx fluxfast init` to refresh this file. -->";
export const FLUXFAST_AGENT_BLOCK_START =
  "<!-- fluxfast-agent-knowledge:start -->";
export const FLUXFAST_AGENT_BLOCK_END =
  "<!-- fluxfast-agent-knowledge:end -->";

export type AgentInstructionMerge =
  | { status: "unchanged"; content: string }
  | { status: "updated"; content: string }
  | { status: "malformed" };

function displayPath(project: FluxProjectInfo, target: string): string {
  return path.relative(project.root, target).replace(/\\/g, "/") || ".";
}

function packageVersion(pkg: DetectedPackage, fallback?: string): string {
  const exactVersion = [pkg.installedVersion, fallback].find(value =>
    value
      ? /^v?\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(
          value
        )
      : false
  );
  if (exactVersion) return exactVersion;
  return pkg.effectiveVersion || pkg.declaredVersion
    ? "declared; exact installed version not detected"
    : "not detected";
}

export function desiredAgentKnowledgePath(project: FluxProjectInfo): string {
  return path.join(project.generatedDir, "agent-knowledge.md");
}

export function desiredAgentInstructionPaths(project: FluxProjectInfo): string[] {
  return [
    path.join(project.root, "AGENTS.md"),
    path.join(project.root, "CLAUDE.md"),
  ];
}

export function isFluxFastAgentKnowledge(content: string): boolean {
  return content.startsWith(FLUXFAST_AGENT_KNOWLEDGE_MARKER);
}

export function renderAgentInstructionBlock(project: FluxProjectInfo): string {
  const knowledgePath = displayPath(project, desiredAgentKnowledgePath(project));
  return [
    FLUXFAST_AGENT_BLOCK_START,
    "## FluxFast",
    "",
    `@${knowledgePath}`,
    "",
    `Read and follow [the generated FluxFast agent knowledge](${knowledgePath}) before changing FluxFast application code or configuration.`,
    FLUXFAST_AGENT_BLOCK_END,
  ].join("\n");
}

export function mergeAgentInstructionBlock(
  existing: string,
  block: string
): AgentInstructionMerge {
  const newline = existing.includes("\r\n") ? "\r\n" : "\n";
  const managedBlock = newline === "\n" ? block : block.replace(/\n/g, newline);
  const start = existing.indexOf(FLUXFAST_AGENT_BLOCK_START);
  const end = existing.indexOf(FLUXFAST_AGENT_BLOCK_END);

  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    return { status: "malformed" };
  }

  if (start === -1) {
    const prefix =
      existing.length === 0
        ? ""
        : existing.endsWith("\n")
          ? newline
          : `${newline}${newline}`;
    return {
      status: "updated",
      content: `${existing}${prefix}${managedBlock}${newline}`,
    };
  }

  const suffixStart = end + FLUXFAST_AGENT_BLOCK_END.length;
  if (
    existing.indexOf(FLUXFAST_AGENT_BLOCK_START, start + 1) !== -1 ||
    existing.indexOf(FLUXFAST_AGENT_BLOCK_END, end + 1) !== -1
  ) {
    return { status: "malformed" };
  }
  const content =
    `${existing.slice(0, start)}${managedBlock}${existing.slice(suffixStart)}`;
  return content === existing
    ? { status: "unchanged", content }
    : { status: "updated", content };
}

/** Render the self-contained integration knowledge imported by project agent files. */
export function renderAgentKnowledge(project: FluxProjectInfo): string {
  const configPath = displayPath(project, project.configPath);
  const pagesPath = displayPath(project, project.fluxPagesDir);
  const generatedPath = displayPath(project, project.generatedDir);
  const nextVersion = packageVersion(project.packages.fluxfastNext);
  const coreVersion = packageVersion(
    project.packages.fluxfastCore,
    project.packages.fluxfastAdapterCoreVersion
  );
  const generatedTypesImport = project.usesAtAlias
    ? "@/.fluxfast/types.generated"
    : "../../.fluxfast/types.generated";

  return [
    FLUXFAST_AGENT_KNOWLEDGE_MARKER,
    "",
    "# FluxFast agent knowledge",
    "",
    "Use this guide when planning, implementing, reviewing, or debugging FluxFast application code in this project. It records package-specific decisions that are easy for a general coding agent to get wrong. It is generated by the installed adapter; do not edit it manually.",
    "",
    "## Detected project",
    "",
    `- \`@fluxfast/next\`: \`${nextVersion}\``,
    `- \`@fluxfast/core\`: \`${coreVersion}\``,
    `- Application components: \`${pagesPath}/\``,
    `- Adapter configuration: \`${configPath}\``,
    `- Generated artifacts: \`${generatedPath}/\``,
    "",
    "If these paths or versions no longer match the project, run `npx fluxfast init` before relying on this guide.",
    "",
    "## Architecture and ownership",
    "",
    "FluxFast synchronizes named resources between FastAPI and a frontend shell. It does not move application routing or authorization into Next.js.",
    "",
    "- FastAPI owns application URLs, authentication, authorization, input validation, resource declarations, mutations, redirects, and the selected component identifier.",
    "- The frontend registry maps the server-selected component identifier to an allowlisted module under the application-components directory.",
    "- `@fluxfast/core` is framework-neutral. Never introduce React, Next.js, Vue, Svelte, Solid, or browser-framework dependencies into Core code.",
    "- `@fluxfast/next` owns React hooks, the Next.js shell, server handlers, the component registry, and same-origin transport integration.",
    "- The browser protocol, developer schema, Python package version, and JavaScript package versions are separate contracts. Do not infer one version from another.",
    "",
    "The normal data flow is:",
    "",
    "```text",
    "FastAPI route and dependencies",
    "  -> Page(component, resources)",
    "  -> resource engine and scoped cache",
    "  -> fluxfast/1 envelope",
    "  -> @fluxfast/core stores/router",
    "  -> @fluxfast/next component and hooks",
    "```",
    "",
    "Fix behavior in the layer that owns it. Do not compensate for an incorrect backend contract with frontend parsing, or for a frontend registry problem with a backend route workaround.",
    "",
    "## Generated files",
    "",
    `Treat every generated file under \`${generatedPath}/\` as read-only, including this guide. Typical artifacts are:`,
    "",
    "- `schema.generated.json`: validated backend contract manifest.",
    "- `types.generated.ts`: application models, resource values, and `resourceKeys`.",
    "- `validators.generated.ts`: native client validators.",
    "- `routes.generated.ts`: typed page URL builders.",
    "- `mutations.generated.ts`: typed JSON mutation helpers.",
    "- `pages.generated.ts`: allowlisted lazy component registry.",
    "- `agent-knowledge.md`: this generated integration guide.",
    "",
    "Change Python declarations, frontend page modules, or FluxFast configuration and regenerate. Never patch generated TypeScript to make a build pass.",
    "",
    "## Backend page and resource pattern",
    "",
    "Declare typed resources once and return them from a FastAPI-owned page. Every cached resource must have an intentional isolation scope.",
    "",
    "```python",
    "from fluxfast import FluxFast, Page, resource, scope",
    "",
    "flux = FluxFast(app)",
    "ROOMS = flux.define_resource(\"rooms\", list[Room])",
    "",
    "@app.get(\"/hotels/{hotel_id}/rooms\")",
    "async def rooms_page(hotel_id: int, user: User = Depends(current_user)) -> Page:",
    "    return Page(",
    "        component=\"rooms/index\",",
    "        resources=[",
    "            resource(",
    "                ROOMS,",
    "                lambda: repository.list_rooms(hotel_id),",
    "                scope=scope.tenant(user.hotel_id),",
    "                ttl=30,",
    "            )",
    "        ],",
    "    )",
    "```",
    "",
    "Resource rules:",
    "",
    "- Use `scope.public()` only for values that are identical for every caller.",
    "- Use `scope.user(id)` or `scope.tenant(id)` for protected or tenant-specific values. Never cache authenticated data without an explicit reusable scope.",
    "- Use request scope or disable caching when a value cannot safely be reused.",
    "- Keep loaders canonical: the same key and scope must represent the same JSON value contract.",
    "- Pydantic validation and serialization on the server remain authoritative even when a client validator exists.",
    "- Authentication and authorization dependencies run for page visits, partial resource loads, deferred loads, and live subscription authorization. Do not authorize only during the first document request.",
    "",
    "## Frontend resource pattern",
    "",
    "Use generated keys so hooks infer the generated resource value type.",
    "",
    "```tsx",
    "\"use client\";",
    "",
    "import { useResource } from \"@fluxfast/next\";",
    `import { resourceKeys } from \"${generatedTypesImport}\";`,
    "",
    "export default function RoomsPage() {",
    "  const rooms = useResource(resourceKeys.rooms);",
    "  return <RoomList rooms={rooms} />;",
    "}",
    "```",
    "",
    "Component identifiers must exactly match the generated registry key, such as `rooms/index`. Never turn an arbitrary server string into a dynamic filesystem import.",
    "",
    "## Mutations",
    "",
    "Mutations are FastAPI operations. Return structured patches, invalidations, or redirects instead of inventing a second client state protocol.",
    "",
    "```python",
    "from fluxfast import MutationResult, append_item, mutation",
    "",
    "@app.post(\"/rooms\")",
    "async def create_room(payload: CreateRoomBody) -> MutationResult:",
    "    created = await repository.create_room(payload)",
    "    return mutation(patches={\"rooms\": append_item(created)})",
    "```",
    "",
    "Use a scoped invalidation when the server cannot express the authoritative result as a safe patch. The invalidation scope must match the resource declaration. A mutation may already have committed when a request is cancelled, so do not assume cancellation rolls back server work.",
    "",
    "## Deferred and live resources",
    "",
    "- `defer=True` delays only the loader. The page route, dependencies, authentication, validation, and authorization still run before each resource envelope.",
    "- Consume a possibly pending value with `useDeferredResource`; provide loading, failure, and retry UI instead of treating it as immediately available.",
    "- `live=True` subscribes the client to invalidation, patch, or resynchronization signals. The broker coordinates signals; the resource loader remains the source of canonical data.",
    "- Live events and deferred responses race with navigation, mutations, logout, and retries. Use existing FluxFast lifecycle APIs rather than adding uncoordinated fetches or stores.",
    "- Use Redis cache and broker implementations for coordination across multiple workers. In-memory implementations are process-local.",
    "",
    "## Routing and transport",
    "",
    "- Keep FastAPI as the application router. Next.js provides the document shell, component compilation, and code splitting.",
    "- Prefer the generated same-origin transport. The browser should normally call relative URLs and should not need the private FastAPI port or CORS configuration.",
    "- `backendUrl` is server-visible. Set `clientUrl` only for a deliberate cross-origin browser deployment.",
    "- Use FluxFast internal redirects for safe origin-relative navigation and external redirects only for deliberate absolute HTTP(S) destinations.",
    "- Do not forward arbitrary incoming headers to the backend. Preserve the adapter's bounded safe-header policy.",
    "",
    "## Contracts and validation",
    "",
    "Define application contracts in Python and regenerate the frontend representation:",
    "",
    "```bash",
    "fluxfast types backend.main:app --frontend frontend",
    "fluxfast types backend.main:app --frontend frontend --check",
    "```",
    "",
    "Use the path that matches the repository layout; omit `--frontend` when the frontend is the current directory. Generated browser validation improves feedback but never replaces Pydantic validation, authorization, or business rules on FastAPI.",
    "",
    "Do not make an incompatible `fluxfast/1` wire change or `fluxfast-schema/2` manifest change as an application workaround. Package APIs, wire protocol, and developer schema have independent compatibility rules.",
    "",
    "## Commands for agents",
    "",
    "Run commands from the detected frontend project unless the command imports the Python application.",
    "",
    "```bash",
    "npx fluxfast init --dry-run  # preview scaffold and managed-agent changes",
    "npx fluxfast init            # apply safe scaffold and refresh this guide",
    "npx fluxfast generate        # regenerate the page registry and typed artifacts",
    "npx fluxfast generate --check",
    "npx fluxfast doctor",
    "```",
    "",
    "The Python supervisor selects npm, pnpm, Yarn, or Bun for the frontend. Do not require pnpm in a consuming application merely because FluxFast itself uses pnpm.",
    "",
    "## Change routing",
    "",
    "| Desired change | Owning location | Expected verification |",
    "| --- | --- | --- |",
    "| URL, auth, authorization, resource, mutation, redirect | FastAPI application | Python tests plus contract generation/check |",
    `| Page UI | \`${pagesPath}/\` | frontend typecheck/build and relevant UI tests |`,
    `| Registry or generated types | authoritative pages/Python contracts, then generator | \`fluxfast generate --check\` or \`fluxfast types ... --check\` |`,
    `| Adapter options | \`${configPath}\` | \`npx fluxfast doctor\` and Next.js build |`,
    "| Framework-neutral navigation/cache/store behavior | `@fluxfast/core` | Core tests; no React/Next imports |",
    "| React or Next.js integration | `@fluxfast/next` | adapter tests and Next.js consumer build |",
    "| Browser envelope fields or semantics | protocol-owning packages and protocol documentation | cross-language protocol fixtures |",
    "",
    "## Review checklist",
    "",
    "Before completing a FluxFast application change, verify the items that apply:",
    "",
    "1. FastAPI still owns routing, authorization, validation, and selected component identifiers.",
    "2. Every cached value has the correct public, user, tenant, custom, or request isolation scope.",
    "3. Mutation invalidations use the same key and scope as their resources.",
    "4. Generated files were regenerated rather than manually edited.",
    "5. Deferred and live states have pending, error, retry, navigation, and logout behavior considered.",
    "6. The browser uses same-origin transport unless cross-origin behavior is intentional and configured.",
    "7. Python tests, frontend typecheck/build, generated-artifact checks, and relevant end-to-end tests pass.",
    "8. Logs and protocol errors do not expose credentials, scope identities, or untrusted backend details.",
    "",
    "## Authoritative references",
    "",
    "When a change needs deeper detail, use the maintained documentation instead of guessing:",
    "",
    "- Architecture: https://el37628.github.io/FluxFast-Docs/architecture/",
    "- Quickstart: https://el37628.github.io/FluxFast-Docs/getting-started/",
    "- Resources and caching: https://el37628.github.io/FluxFast-Docs/caching/",
    "- Next.js adapter and CLI: https://el37628.github.io/FluxFast-Docs/nextjs-adapter/",
    "- Generated artifacts: https://el37628.github.io/FluxFast-Docs/generated-artifacts/",
    "- Stable APIs: https://el37628.github.io/FluxFast-Docs/stable-apis/",
    "- Advanced Stable APIs: https://el37628.github.io/FluxFast-Docs/advanced-stable-apis/",
    "",
  ].join("\n");
}
