import path from "node:path";
import type { FluxProjectInfo } from "./types.js";

export const FLUXFAST_GENERATED_MARKER = "// GENERATED BY FLUXFAST.";
export const FLUXFAST_PUBLIC_ROUTE_SEGMENT = "fluxfast";
export const FLUXFAST_LEGACY_ROUTE_SEGMENT = "%5Ffluxfast";

export function isFluxCatchAll(content: string): boolean {
  return (
    /\bcreateFluxNextPage\s*\(/.test(content) &&
    /\bfluxConfig\b/.test(content)
  );
}

export function isFluxHealthRoute(content: string): boolean {
  return (
    content.includes(FLUXFAST_GENERATED_MARKER) &&
    /\bcreateFluxHealthHandler\s*\(/.test(content)
  );
}

export function isFluxTransportRoute(content: string): boolean {
  return (
    content.includes(FLUXFAST_GENERATED_MARKER) &&
    /\bcreateFluxTransportHandler\s*\(/.test(content)
  );
}

type RelativePathApi = Pick<typeof path, "dirname" | "relative">;

function withoutSourceExtension(filePath: string): string {
  return filePath.replace(/\.(?:tsx?|jsx?)$/, "");
}

/** Build a portable relative ESM specifier between two source files. */
export function relativeImport(
  fromFile: string,
  toFile: string,
  pathApi: RelativePathApi = path
): string {
  const relative = pathApi
    .relative(pathApi.dirname(fromFile), withoutSourceExtension(toFile))
    .replace(/\\/g, "/");
  return relative.startsWith("./") || relative.startsWith("../")
    ? relative
    : `./${relative}`;
}

export function desiredCatchAllPath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "tsx" : "jsx";
  return path.join(
    project.appDir,
    "(flux)",
    "[[...flux]]",
    `page.${extension}`
  );
}

export function desiredHomePagePath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "tsx" : "jsx";
  return path.join(project.fluxPagesDir, "home", `index.${extension}`);
}

export function desiredHealthRoutePath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "ts" : "js";
  return path.join(
    project.appDir,
    FLUXFAST_PUBLIC_ROUTE_SEGMENT,
    "[probe]",
    `route.${extension}`
  );
}

export function desiredTransportRoutePath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "ts" : "js";
  return path.join(
    project.appDir,
    FLUXFAST_PUBLIC_ROUTE_SEGMENT,
    "transport",
    "[[...path]]",
    `route.${extension}`
  );
}

export function legacyHealthRoutePath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "ts" : "js";
  return path.join(
    project.appDir,
    FLUXFAST_LEGACY_ROUTE_SEGMENT,
    "[probe]",
    `route.${extension}`
  );
}

export function legacyTransportRoutePath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "ts" : "js";
  return path.join(
    project.appDir,
    FLUXFAST_LEGACY_ROUTE_SEGMENT,
    "transport",
    "[[...path]]",
    `route.${extension}`
  );
}

export function legacyRouteRoot(project: FluxProjectInfo): string {
  return path.join(project.appDir, FLUXFAST_LEGACY_ROUTE_SEGMENT);
}

function configImportForCatchAll(
  project: FluxProjectInfo,
  catchAllPath: string
): string {
  return project.usesAtAlias
    ? "@/fluxfast.config"
    : relativeImport(catchAllPath, project.configPath);
}

function registryImportForConfig(project: FluxProjectInfo): string {
  return project.usesAtAlias
    ? "@/.fluxfast/pages.generated"
    : relativeImport(project.configPath, project.registryPath);
}

export function renderCatchAll(project: FluxProjectInfo): string {
  const catchAllPath = desiredCatchAllPath(project);
  return `${FLUXFAST_GENERATED_MARKER}\n// Run \`fluxfast init --force\` to repair this file.\n\nimport { createFluxNextPage } from "@fluxfast/next/server";\nimport { fluxConfig } from ${JSON.stringify(configImportForCatchAll(project, catchAllPath))};\n\nexport const dynamic = "force-dynamic";\n\nexport default createFluxNextPage(fluxConfig);\n`;
}

export function renderHealthRoute(): string {
  return `${FLUXFAST_GENERATED_MARKER}\n// Run \`fluxfast init --force\` to repair this file.\n\nimport { createFluxHealthHandler } from "@fluxfast/next/server";\n\nexport const dynamic = "force-dynamic";\nexport const GET = createFluxHealthHandler();\n`;
}

export function renderTransportRoute(): string {
  return `${FLUXFAST_GENERATED_MARKER}\n// Run \`fluxfast init --force\` to repair this file.\n\nimport { createFluxTransportHandler } from "@fluxfast/next/server";\n\nexport const dynamic = "force-dynamic";\nconst transport = createFluxTransportHandler();\n\nexport const GET = transport;\nexport const HEAD = transport;\nexport const POST = transport;\nexport const PUT = transport;\nexport const PATCH = transport;\nexport const DELETE = transport;\n`;
}

export function renderFluxConfig(project: FluxProjectInfo): string {
  return `import { defineFluxConfig } from "@fluxfast/next";\nimport { FluxApplication } from ${JSON.stringify(registryImportForConfig(project))};\n\nexport const fluxConfig = defineFluxConfig({\n  application: FluxApplication,\n});\n`;
}

export function renderStarterPage(): string {
  return `"use client";\n\nexport default function HomePage() {\n  return (\n    <main>\n      <h1>FluxFast</h1>\n      <p>Your FluxFast frontend is ready.</p>\n    </main>\n  );\n}\n`;
}
