import path from "node:path";
import type { FluxProjectInfo } from "./types";

export const FLUXFAST_GENERATED_MARKER = "// GENERATED BY FLUXFAST.";

type RelativePathApi = Pick<typeof path, "dirname" | "relative">;

function withoutSourceExtension(filePath: string): string {
  return filePath.replace(/\.(?:tsx?|jsx?)$/, "");
}

/** Build a portable relative ESM specifier between two source files. */
export function relativeImport(
  fromFile: string,
  toFile: string,
  pathApi: RelativePathApi = path
): string {
  const relative = pathApi
    .relative(pathApi.dirname(fromFile), withoutSourceExtension(toFile))
    .replace(/\\/g, "/");
  return relative.startsWith("./") || relative.startsWith("../")
    ? relative
    : `./${relative}`;
}

export function desiredCatchAllPath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "tsx" : "jsx";
  return path.join(
    project.appDir,
    "(flux)",
    "[[...flux]]",
    `page.${extension}`
  );
}

export function desiredHomePagePath(project: FluxProjectInfo): string {
  const extension = project.language === "typescript" ? "tsx" : "jsx";
  return path.join(project.fluxPagesDir, "home", `index.${extension}`);
}

function configImportForCatchAll(
  project: FluxProjectInfo,
  catchAllPath: string
): string {
  return project.usesAtAlias
    ? "@/fluxfast.config"
    : relativeImport(catchAllPath, project.configPath);
}

function registryImportForConfig(project: FluxProjectInfo): string {
  return project.usesAtAlias
    ? "@/.fluxfast/pages.generated"
    : relativeImport(project.configPath, project.registryPath);
}

export function renderCatchAll(project: FluxProjectInfo): string {
  const catchAllPath = desiredCatchAllPath(project);
  return `${FLUXFAST_GENERATED_MARKER}\n// Run \`fluxfast init --force\` to repair this file.\n\nimport { createFluxNextPage } from "@fluxfast/next/server";\nimport { fluxConfig } from ${JSON.stringify(configImportForCatchAll(project, catchAllPath))};\n\nexport const dynamic = "force-dynamic";\n\nexport default createFluxNextPage(fluxConfig);\n`;
}

export function renderFluxConfig(project: FluxProjectInfo): string {
  return `import { defineFluxConfig } from "@fluxfast/next";\nimport { FluxApplication } from ${JSON.stringify(registryImportForConfig(project))};\n\nexport const fluxConfig = defineFluxConfig({\n  application: FluxApplication,\n});\n`;
}

export function renderStarterPage(): string {
  return `"use client";\n\nexport default function HomePage() {\n  return (\n    <main>\n      <h1>FluxFast</h1>\n      <p>Your FluxFast frontend is ready.</p>\n    </main>\n  );\n}\n`;
}
