"""FluxFast — high-performance server-driven application runtime for FastAPI."""

__version__ = "0.8.0"

from .app import FluxFast
from .cache import CachedResource, MemoryResourceCache, ResourceCacheBackend
from .cache_metrics import RedisCacheMetrics, RedisCacheMetricsSnapshot
from .capabilities import (
    CAPABILITY_DEFERRED_RESOURCES,
    CAPABILITY_LIVE_RESOURCES,
    client_supports,
)
from .contract import ContractMode, ResourceContract, TypeContract
from .errors import (
    FluxFastError,
    FluxFastLiveScopeError,
    PageNotFoundError,
    ProtocolError,
    ResourceCacheError,
    ResourceCacheSerializationError,
    ResourceCacheUnavailableError,
    ResourceContractError,
    ResourceError,
    ScopeError,
    ValidationError,
)
from .headers import HEADER_CAPABILITIES
from .live import (
    DEFAULT_LIVE_HEARTBEAT_INTERVAL,
    DEFAULT_LIVE_MAX_CONNECTION_AGE,
    DEFAULT_LIVE_QUEUE_SIZE,
    DEFAULT_REDIS_CHANNEL_PREFIX,
    DEFAULT_REDIS_MAX_MESSAGE_BYTES,
    LIVE_EVENT_NAME,
    LIVE_HEARTBEAT,
    LIVE_RESYNC_REASONS,
    LiveBroker,
    LiveCoordinator,
    LiveEvent,
    LiveInvalidateEvent,
    LiveMetrics,
    LiveMetricsSnapshot,
    LivePatchEvent,
    LiveReadyEvent,
    LiveResyncEvent,
    LiveResyncReason,
    LiveSubscription,
    MemoryLiveBroker,
    RedisLiveBroker,
    derive_live_topic,
    encode_sse_event,
    iter_live_events,
)
from .mutation import (
    InvalidateResource,
    MutationResult,
    append_item,
    flux_external_redirect,
    flux_redirect,
    invalidate_resource,
    merge_object,
    mutation,
    remove_item,
    replace_item,
    replace_resource,
)
from .page import Page
from .protocol import (
    PROTOCOL_MEDIA_TYPE,
    PROTOCOL_VERSION,
    ErrorDetail,
    ErrorEnvelope,
    MutationEnvelope,
    MutationPayload,
    PageDescriptor,
    PageEnvelope,
    ResourceErrorDetail,
    ResourceWireRecord,
)
from .redis_cache import (
    DEFAULT_REDIS_MAX_VALUE_BYTES,
    DEFAULT_REDIS_SCAN_COUNT,
    RedisResourceCache,
)
from .resource import ResourceLoader, ResourceSpec, resource
from .router import FluxRouter
from .scope import CacheScope, ScopeType, scope

__all__ = [
    "CAPABILITY_DEFERRED_RESOURCES",
    "CAPABILITY_LIVE_RESOURCES",
    "DEFAULT_LIVE_HEARTBEAT_INTERVAL",
    "DEFAULT_LIVE_MAX_CONNECTION_AGE",
    "DEFAULT_LIVE_QUEUE_SIZE",
    "DEFAULT_REDIS_CHANNEL_PREFIX",
    "DEFAULT_REDIS_MAX_MESSAGE_BYTES",
    "DEFAULT_REDIS_MAX_VALUE_BYTES",
    "DEFAULT_REDIS_SCAN_COUNT",
    "HEADER_CAPABILITIES",
    "LIVE_EVENT_NAME",
    "LIVE_HEARTBEAT",
    "LIVE_RESYNC_REASONS",
    "PROTOCOL_MEDIA_TYPE",
    "PROTOCOL_VERSION",
    "CacheScope",
    "CachedResource",
    "ContractMode",
    "ErrorDetail",
    "ErrorEnvelope",
    "FluxFast",
    "FluxFastError",
    "FluxFastLiveScopeError",
    "FluxRouter",
    "InvalidateResource",
    "LiveBroker",
    "LiveCoordinator",
    "LiveEvent",
    "LiveInvalidateEvent",
    "LiveMetrics",
    "LiveMetricsSnapshot",
    "LivePatchEvent",
    "LiveReadyEvent",
    "LiveResyncEvent",
    "LiveResyncReason",
    "LiveSubscription",
    "MemoryLiveBroker",
    "MemoryResourceCache",
    "MutationEnvelope",
    "MutationPayload",
    "MutationResult",
    "Page",
    "PageDescriptor",
    "PageEnvelope",
    "PageNotFoundError",
    "ProtocolError",
    "RedisCacheMetrics",
    "RedisCacheMetricsSnapshot",
    "RedisLiveBroker",
    "RedisResourceCache",
    "ResourceCacheBackend",
    "ResourceCacheError",
    "ResourceCacheSerializationError",
    "ResourceCacheUnavailableError",
    "ResourceContract",
    "ResourceContractError",
    "ResourceError",
    "ResourceErrorDetail",
    "ResourceLoader",
    "ResourceSpec",
    "ResourceWireRecord",
    "ScopeError",
    "ScopeType",
    "TypeContract",
    "ValidationError",
    "append_item",
    "client_supports",
    "derive_live_topic",
    "encode_sse_event",
    "flux_external_redirect",
    "flux_redirect",
    "invalidate_resource",
    "iter_live_events",
    "merge_object",
    "mutation",
    "remove_item",
    "replace_item",
    "replace_resource",
    "resource",
    "scope",
]
