"""FluxFast — high-performance server-driven application runtime for FastAPI."""

from .app import FluxFast
from .cache import CachedResource, MemoryResourceCache, ResourceCacheBackend
from .capabilities import (
    CAPABILITY_DEFERRED_RESOURCES,
    CAPABILITY_LIVE_RESOURCES,
    client_supports,
)
from .errors import (
    FluxFastError,
    FluxFastLiveScopeError,
    PageNotFoundError,
    ProtocolError,
    ResourceError,
    ScopeError,
    ValidationError,
)
from .headers import HEADER_CAPABILITIES
from .live import (
    DEFAULT_LIVE_QUEUE_SIZE,
    LIVE_EVENT_NAME,
    LIVE_RESYNC_REASONS,
    LiveBroker,
    LiveCoordinator,
    LiveEvent,
    LiveInvalidateEvent,
    LivePatchEvent,
    LiveReadyEvent,
    LiveResyncEvent,
    LiveResyncReason,
    LiveSubscription,
    MemoryLiveBroker,
    derive_live_topic,
)
from .mutation import (
    InvalidateResource,
    MutationResult,
    append_item,
    flux_external_redirect,
    flux_redirect,
    invalidate_resource,
    merge_object,
    mutation,
    remove_item,
    replace_item,
    replace_resource,
)
from .page import Page
from .protocol import (
    PROTOCOL_MEDIA_TYPE,
    PROTOCOL_VERSION,
    ErrorDetail,
    ErrorEnvelope,
    MutationEnvelope,
    MutationPayload,
    PageDescriptor,
    PageEnvelope,
    ResourceErrorDetail,
    ResourceWireRecord,
)
from .resource import ResourceLoader, ResourceSpec, resource
from .router import FluxRouter
from .scope import CacheScope, ScopeType, scope

__version__ = "0.3.0"

__all__ = [
    "CAPABILITY_DEFERRED_RESOURCES",
    "CAPABILITY_LIVE_RESOURCES",
    "DEFAULT_LIVE_QUEUE_SIZE",
    "HEADER_CAPABILITIES",
    "LIVE_EVENT_NAME",
    "LIVE_RESYNC_REASONS",
    "PROTOCOL_MEDIA_TYPE",
    "PROTOCOL_VERSION",
    "CacheScope",
    "CachedResource",
    "ErrorDetail",
    "ErrorEnvelope",
    "FluxFast",
    "FluxFastError",
    "FluxFastLiveScopeError",
    "FluxRouter",
    "InvalidateResource",
    "LiveBroker",
    "LiveCoordinator",
    "LiveEvent",
    "LiveInvalidateEvent",
    "LivePatchEvent",
    "LiveReadyEvent",
    "LiveResyncEvent",
    "LiveResyncReason",
    "LiveSubscription",
    "MemoryLiveBroker",
    "MemoryResourceCache",
    "MutationEnvelope",
    "MutationPayload",
    "MutationResult",
    "Page",
    "PageDescriptor",
    "PageEnvelope",
    "PageNotFoundError",
    "ProtocolError",
    "ResourceCacheBackend",
    "ResourceError",
    "ResourceErrorDetail",
    "ResourceLoader",
    "ResourceSpec",
    "ResourceWireRecord",
    "ScopeError",
    "ScopeType",
    "ValidationError",
    "append_item",
    "client_supports",
    "derive_live_topic",
    "flux_external_redirect",
    "flux_redirect",
    "invalidate_resource",
    "merge_object",
    "mutation",
    "remove_item",
    "replace_item",
    "replace_resource",
    "resource",
    "scope",
]
