import { relativeFile, HOST_CONFIG, type FrontendProject } from "./project.js";

export const KNOWLEDGE_MARKER = "<!-- GENERATED BY FLUXFAST. Run `fluxfast-vite init` to refresh this file. -->";
const START = "<!-- fluxfast-agent-knowledge:start -->";
const END = "<!-- fluxfast-agent-knowledge:end -->";

/** Replace only the one bounded managed block; preserve surrounding text and CRLF. */
export function mergeAgentBlock(existing: string, knowledge: string): string {
  const newline = existing.includes("\r\n") ? "\r\n" : "\n";
  const block = [START, "## FluxFast", "", "@" + knowledge, "",
    `Read [the generated FluxFast knowledge](${knowledge}) before changing FluxFast application code or configuration.`, END].join(newline);
  const start = existing.indexOf(START);
  const end = existing.indexOf(END);
  if ((start === -1) !== (end === -1) || end < start ||
      start !== -1 && (existing.indexOf(START, start + 1) !== -1 || existing.indexOf(END, end + 1) !== -1)) throw new Error("Malformed or duplicate FluxFast agent blocks; repair the markers without deleting user instructions");
  if (start === -1) return existing + (existing ? (existing.endsWith("\n") ? newline : newline + newline) : "") + block + newline;
  return existing.slice(0, start) + block + existing.slice(end + END.length);
}

export function renderKnowledge(project: FrontendProject): string {
  const pages = relativeFile(project, project.pages);
  const generated = relativeFile(project, project.generated);
  return `${KNOWLEDGE_MARKER}

# FluxFast React/Vite agent knowledge

This is generated integration knowledge, not user instructions. Do not edit this
file; refresh it with the installed \`fluxfast-vite init\` command. Resolve exact
package versions from the lockfile, not framework or protocol version guesses.

## Architecture and ownership

- FastAPI owns application URLs, authentication, authorization, input validation,
  named resources, mutations, redirects and selected component identifiers.
- \`@fluxfast/core\` owns the framework-neutral stores, router, reconciliation,
  deferred/live lifecycle and protocol validation. Never put framework imports in Core.
- \`@fluxfast/react\` provides hooks, registry rendering, SSR and exact-envelope
  hydration. \`@fluxfast/vite\` provides compilation, assets and the Node host.
- The allowlist in \`${generated}/pages.generated.ts\` selects modules under
  \`${pages}/\`. Never dynamically import arbitrary backend component strings.
- Python package, JavaScript packages, \`fluxfast/1\` and \`fluxfast-schema/2\`
  are separate versioned contracts; do not infer a protocol version from a package.

## Files and commands

The dedicated host config is \`${HOST_CONFIG}\`, extending an existing Vite
config when present. It is evaluated during development/build, never production
startup. \`fluxfast.html\` contains exactly one SSR marker inside
\`#fluxfast-root\` and one payload marker outside it. Preserve both.

Existing SPA entry files and scripts are user-owned. Use the scoped host scripts:

\`\`\`sh
npm run fluxfast:dev
npm run fluxfast:build
npm run fluxfast:start
npm exec --no -- fluxfast-vite generate
npm exec --no -- fluxfast-vite generate --check
npm exec --no -- fluxfast-vite init --check
npm exec --no -- fluxfast-vite doctor
\`\`\`

With matching Python and JavaScript packages, run the whole application from its
backend project directory. Python detects \`@fluxfast/vite\` and selects the
scoped scripts without changing your SPA scripts:

\`\`\`sh
fluxfast types backend.main:app --frontend frontend
fluxfast types backend.main:app --frontend frontend --check
fluxfast dev backend.main:app --frontend frontend
fluxfast build --app backend.main:app --frontend frontend
fluxfast doctor --production --app backend.main:app --frontend frontend --strict
fluxfast start backend.main:app --frontend frontend
\`\`\`

Development and production supervise FastAPI and the Node host behind one public
origin. Do not run a second FastAPI service alongside these supervised commands.
The frontend-only scripts above are for advanced, manually supervised hosts;
only that mode requires setting the private backend URL yourself.

Use the project's installed npm, pnpm, Yarn or Bun tooling; initialization never
downloads dependencies. Full-stack generation starts from the authoritative Python
contracts and the developer schema. Do not patch generated TypeScript to pass a build.
All six artifacts under \`${generated}/\` and this guide are generated.

## Page declaration and input/output

\`\`\`python
from fastapi import FastAPI
from fluxfast import FluxFast, Page, resource, scope

app = FastAPI()
flux = FluxFast(app)
GREETING = flux.define_resource("greeting", str)

@flux.page("/", name="home")
async def home() -> Page:
    return Page(component="home/index", resources=[
        resource(GREETING, lambda: "Hello", scope=scope.public(), ttl=30),
    ])
\`\`\`

\`\`\`tsx
import { useResource, Link } from "@fluxfast/react";

export default function Home() {
  const greeting = useResource<string>("greeting");
  return <main><h1>{greeting}</h1><Link href="/rooms">Rooms</Link></main>;
}
\`\`\`

The backend selects \`home/index\` and the canonical greeting. The matching
\`${pages}/home/index.tsx\` (or JSX) produces \`<h1>Hello</h1>\` in the initial
HTML. Hydration must reuse that exact envelope and opaque resource version,
not perform an immediate duplicate initial fetch or replace SSR with an empty SPA.

## Resources, mutations and isolation

- Public scope is only for values identical for every caller. Protected caches
  require \`scope.user(id)\`, \`scope.tenant(id)\`, request scope or no caching.
- Authorize every page, partial/deferred load, mutation and live subscription.
  Consider logout, tenant changes and multiple FastAPI workers in every change.
- Keep canonical loaders and structured mutation patches/invalidation. Cancellation
  does not imply that a server mutation rolled back.
- Use \`useDeferredResource\` for pending/error/retry UI and \`useLiveStatus\`
  for connection state. Do not add a competing store or ad hoc SSE/fetch lifecycle.
- Redis coordinates shared caches and live brokers across workers; memory is local.
- Pydantic validation and authorization remain authoritative even with client validators.

## Same-origin runtime and review

The browser sees one public host for documents, assets and protocol requests.
Only Node receives server-private \`FLUXFAST_BACKEND_URL\`; never put it in a
\`VITE_*\` variable, browser source or serialized page data. The incoming Host
and forwarded headers must not select the backend. Forward only bounded safe headers.
Production uses \`dist/fluxfast/\`, not source config or a Vite development server;
starting must never install, generate or build implicitly. Keep session cookies,
multiple Set-Cookie fields, streams and cancellation intact. Health probes are minimal.

For synchronization bugs, reproduce with development \`@fluxfast/devtools\`
and inspect Timeline/Resources/Cache/Mutations/Live/Protocol evidence. Diagnostics
must remain value-free and inert in production. Never log credentials, resource
values, request bodies or cache scope identities to compensate.

Before finishing: regenerate/check contracts, run relevant Python and frontend
typecheck/build/tests, inspect the browser graph for server/tooling imports, and
verify SSR, hydration, navigation, deferred/live cleanup and tenant isolation.
Keep FastAPI authoritative and fix the layer that owns the observed behavior.

References: https://el37628.github.io/FluxFast-Docs/ and the installed package README.
`;
}
