import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { mergeAgentBlock, renderKnowledge, KNOWLEDGE_MARKER } from "./agent-knowledge.js";
import { generateProject, validateGeneration } from "./generation.js";
import { assertSafePath, GENERATED_ARTIFACTS, HOST_CONFIG, HOST_SCRIPTS, HOST_TEMPLATE, relativeFile, sourceViteConfig, validatePackages, type FrontendProject } from "./project.js";

const MARKER = "// GENERATED BY FLUXFAST VITE.";
interface Change { file: string; before?: string; after: string }
export interface SetupPlan { project: FrontendProject; changes: Change[] }

function read(project: FrontendProject, file: string): string | undefined {
  assertSafePath(project.root, file);
  try {
    if (!fs.statSync(file).isFile()) throw new Error("A reserved FluxFast scaffold path is not a regular file");
    return fs.readFileSync(file, "utf8");
  } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return; throw error; }
}

function configContent(project: FrontendProject): string {
  const original = sourceViteConfig(project);
  const app = relativeFile(project, project.registry);
  const owned = `{ plugins: [fluxfast({ application: ${JSON.stringify(app)} })] }`;
  if (!original) return `${MARKER}\nimport { fluxfast } from "@fluxfast/vite";\nexport default ${owned};\n`;
  return `${MARKER}
// Existing SPA configuration is preserved and extended only for this host.
import { mergeConfig } from "vite";
import { fluxfast } from "@fluxfast/vite";
import original from ${JSON.stringify("./" + original)};

async function containsFluxPlugin(value) {
  const plugin = await value;
  if (Array.isArray(plugin)) return (await Promise.all(plugin.map(containsFluxPlugin))).some(Boolean);
  return plugin && plugin.name === "fluxfast";
}

export default async context => {
  const config = await (typeof original === "function" ? original(context) : original);
  return mergeConfig(config, {
    plugins: await containsFluxPlugin(config.plugins ?? []) ? [] : [fluxfast({ application: ${JSON.stringify(app)} })],
  });
};
`;
}

const TEMPLATE = '<!-- GENERATED BY FLUXFAST VITE. -->\n<!doctype html>\n<html lang="en">\n  <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>FluxFast</title></head>\n  <body>\n    <div id="fluxfast-root"><!--fluxfast:ssr--></div>\n    <!--fluxfast:payload-->\n    <script type="module" src="/@fluxfast/client"></script>\n  </body>\n</html>\n';
const STARTER = 'export default function Home() {\n  return <main><h1>FluxFast is ready</h1><p>FastAPI owns your application routes and resources.</p></main>;\n}\n';

/** Read-only planning; never evaluate a Vite config or install dependencies. */
export function planSetup(project: FrontendProject, force = false): SetupPlan {
  validatePackages(project);
  validateGeneration(project);
  const changes: Change[] = [];
  const add = (file: string, after: string, policy: "managed" | "preserve" | "knowledge" = "managed", marker = MARKER) => {
    const before = read(project, file);
    if (before === after || before !== undefined && policy === "preserve") return;
    if (before !== undefined) {
      if (policy === "knowledge" && before.startsWith(marker)) { /* Refresh generated knowledge. */ }
      else if (!force) {
        if (before.startsWith(marker)) return; // Preserve customized config/templates.
        throw new Error(`${relativeFile(project, file)} is user-owned; preserve/move it or explicitly use init --force for this reserved file`);
      }
    }
    changes.push({ file, before, after });
  };
  add(path.join(project.root, HOST_CONFIG), configContent(project));
  add(path.join(project.root, HOST_TEMPLATE), TEMPLATE, "managed", "<!-- GENERATED BY FLUXFAST VITE. -->");
  const extension = fs.existsSync(path.join(project.root, "tsconfig.json")) ? "tsx" : "jsx";
  const home = path.join(project.pages, "home");
  const existingHome = ["tsx", "jsx"].find(ext => read(project, path.join(home, "index." + ext)) !== undefined);
  if (!existingHome) add(path.join(home, "index." + extension), STARTER, "preserve");
  const knowledge = path.join(project.generated, "agent-knowledge.md");
  add(knowledge, renderKnowledge(project), "knowledge", KNOWLEDGE_MARKER);
  for (const name of ["AGENTS.md", "CLAUDE.md"]) {
    const file = path.join(project.root, name);
    const before = read(project, file);
    const after = mergeAgentBlock(before ?? "", relativeFile(project, knowledge));
    if (after !== before) changes.push({ file, before, after });
  }
  const originalScripts = project.manifest.scripts ?? {};
  if (!originalScripts || typeof originalScripts !== "object" || Array.isArray(originalScripts) ||
      Object.values(originalScripts).some(value => typeof value !== "string" || !value.trim())) throw new Error("Frontend scripts must contain non-empty command strings");
  const scripts = { ...originalScripts } as Record<string, string>;
  let scriptsChanged = false;
  for (const [name, command] of Object.entries(HOST_SCRIPTS)) {
    if (scripts[name] === undefined) { scripts[name] = command; scriptsChanged = true; }
    else if (!scripts[name].includes("fluxfast-vite " + name.split(":")[1])) throw new Error(`Preserve/rename custom ${name} before adding the FluxFast host script; existing scripts are never overwritten`);
  }
  if (scriptsChanged) changes.push({ file: path.join(project.root, "package.json"), before: project.manifestContent,
    after: JSON.stringify({ ...project.manifest, scripts }, null, 2) + "\n" });
  return { project, changes };
}

function atomicWrite(file: string, content: string | Uint8Array, mode?: number): void {
  const temporary = path.join(path.dirname(file), ".fluxfast-init-" + randomUUID() + ".tmp");
  let descriptor: number | undefined;
  try {
    descriptor = fs.openSync(temporary, "wx", mode);
    fs.writeFileSync(descriptor, content, "utf8"); fs.fsyncSync(descriptor);
    fs.closeSync(descriptor); descriptor = undefined;
    fs.renameSync(temporary, file);
  } finally {
    if (descriptor !== undefined) fs.closeSync(descriptor);
    try { fs.unlinkSync(temporary); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
  }
}

/** Guard the complete plan, apply owned changes, and roll back on generation failure. */
export function applySetup(plan: SetupPlan): void {
  const { project } = plan;
  const targets = [...new Set([...plan.changes.map(change => change.file), ...GENERATED_ARTIFACTS.map(name => path.join(project.generated, name))])];
  const saved = targets.map(file => {
    const content = read(project, file);
    return { file, content: content === undefined ? undefined : fs.readFileSync(file),
      stat: content === undefined ? undefined : fs.statSync(file) };
  });
  for (const change of plan.changes) {
    if (read(project, change.file) !== change.before) throw new Error("A scaffold file changed after planning; rerun initialization without overwriting user work");
  }
  const directories: string[] = [];
  const ensureDirectory = (directory: string): void => {
    assertSafePath(project.root, directory);
    if (fs.existsSync(directory)) return;
    ensureDirectory(path.dirname(directory)); fs.mkdirSync(directory); directories.push(directory);
  };
  try {
    for (const change of plan.changes) {
      ensureDirectory(path.dirname(change.file));
      atomicWrite(change.file, change.after, saved.find(item => item.file === change.file)?.stat?.mode);
    }
    ensureDirectory(project.generated);
    // An already-current initialization is a true no-op, including artifact mtimes.
    if (!generateProject(project, true).current) generateProject(project, false);
  } catch (error) {
    const rollbackFailures: unknown[] = [];
    for (const item of saved.reverse()) {
      try {
        if (item.content === undefined) { if (fs.existsSync(item.file)) fs.unlinkSync(item.file); }
        else {
          const replaced = !fs.existsSync(item.file) || !fs.readFileSync(item.file).equals(item.content);
          if (replaced) atomicWrite(item.file, item.content, item.stat?.mode);
          const current = fs.statSync(item.file);
          if (item.stat && (replaced || current.mode !== item.stat.mode || current.mtimeMs !== item.stat.mtimeMs)) {
            fs.chmodSync(item.file, item.stat.mode);
            fs.utimesSync(item.file, item.stat.atimeMs / 1000, item.stat.mtimeMs / 1000);
          }
        }
      } catch (rollbackError) { rollbackFailures.push(rollbackError); }
    }
    for (const directory of directories.reverse()) { try { fs.rmdirSync(directory); } catch { /* Only remove empty, task-created directories. */ } }
    if (rollbackFailures.length) throw new AggregateError([error, ...rollbackFailures],
      "Initialization failed and rollback was incomplete; inspect scaffold/generated files before retrying");
    throw error;
  }
}

/** Structural, read-only check; the real Vite build remains authoritative. */
export function checkSetup(project: FrontendProject): string[] {
  validatePackages(project);
  const problems: string[] = [];
  const config = read(project, path.join(project.root, HOST_CONFIG));
  if (!config?.includes("@fluxfast/vite") || !config.includes("fluxfast(")) problems.push("Missing FluxFast host config; run fluxfast-vite init");
  const template = read(project, path.join(project.root, HOST_TEMPLATE)) ?? "";
  if ([/<!--fluxfast:ssr-->/g, /<!--fluxfast:payload-->/g, /\bid\s*=\s*(["'])fluxfast-root\1/g, /\bsrc\s*=\s*(["'])\/@fluxfast\/client\1/g]
    .some(marker => [...template.matchAll(marker)].length !== 1)) problems.push("Host template is missing or its SSR/hydration markers are invalid");
  const scripts = project.manifest.scripts as Record<string, unknown> | undefined;
  for (const name of Object.keys(HOST_SCRIPTS)) {
    if (typeof scripts?.[name] !== "string" || !scripts[name].includes("fluxfast-vite " + name.split(":")[1])) problems.push(`Missing scoped ${name} host script`);
  }
  const knowledge = path.join(project.generated, "agent-knowledge.md");
  if (!read(project, knowledge)?.startsWith(KNOWLEDGE_MARKER)) problems.push("Generated agent knowledge is missing; run fluxfast-vite init");
  for (const name of ["AGENTS.md", "CLAUDE.md"]) {
    const content = read(project, path.join(project.root, name)) ?? "";
    try { if (mergeAgentBlock(content, relativeFile(project, knowledge)) !== content) problems.push(`${name} is missing the FluxFast managed reference`); }
    catch { problems.push(`${name} has malformed FluxFast managed markers`); }
  }
  return problems;
}
