// GENERATED BY FLUXFAST VITE. Customized test fixture configuration.
import { fileURLToPath } from "node:url";
import { fluxfast } from "@fluxfast/vite";

export default {
  resolve: { alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) } },
  plugins: [fluxfast({
    application: "src/Application.tsx",
    applicationExport: "Application",
    forwardHeaders: ["authorization"],
    cache: { maxResources: 32, maxPages: 8 },
    diagnostics: true,
  })],
};
