// AUTO-GENERATED BY FLUXFAST.
// DO NOT EDIT MANUALLY.
// Schema: fluxfast-schema/2
// Producer: 1.1.0
// Fingerprint: 541a688a1f3aff53317ebdb67b10aa808479b70529f7d706b5bc9b96a2069a77

import type { FluxRouter, MutationEnvelope } from "@fluxfast/core";
import type { UpdateRoomBody } from "./types.generated";

function appendFluxMutationQuery(
  search: URLSearchParams,
  key: string,
  value: unknown
): void {
  if (value === undefined || value === null) return;
  if (Array.isArray(value)) {
    for (const item of value) appendFluxMutationQuery(search, key, item);
    return;
  }
  search.append(key, String(value));
}

export const mutations = {
  updateRoom: (
    router: FluxRouter,
    input: {
  params: {
    room_id: number;
  };
  query: {
    budget: number | string;
  };
  body: UpdateRoomBody;
}
  ): Promise<MutationEnvelope> => {
    let path = "/rooms/{room_id}";
    path = path.replace("{room_id}", encodeURIComponent(String(input.params["room_id"])));
    const search = new URLSearchParams();
    appendFluxMutationQuery(search, "budget", input.query?.["budget"]);
    const query = search.toString();
    if (query) path = `${path}?${query}`;
    return router.mutate(path, input.body, { method: "PATCH" });
  },
} as const;
