// AUTO-GENERATED BY FLUXFAST.
// DO NOT EDIT MANUALLY.
"use client";

import React from "react";
import { FluxRoot } from "@fluxfast/next";
import type { ComponentRegistry, FluxApplicationProps } from "@fluxfast/next";

export const fluxPages: ComponentRegistry = {
  "(admin)/[room-id]": { load: () => import("../flux-pages/(admin)/[room-id]") },
  "home/index": { load: () => import("../flux-pages/home/index") },
  "hotel_rooms/index": { load: () => import("../flux-pages/hotel_rooms/index") },
  "legacy": { load: () => import("../flux-pages/legacy") },
};

export function FluxApplication(props: FluxApplicationProps) {
  return React.createElement(FluxRoot, { ...props, registry: fluxPages });
}

export default fluxPages;
