// AUTO-GENERATED BY FLUXFAST.
// DO NOT EDIT MANUALLY.
// Schema: fluxfast-schema/2
// Producer: 1.1.0
// Fingerprint: 541a688a1f3aff53317ebdb67b10aa808479b70529f7d706b5bc9b96a2069a77

function appendFluxRouteQuery(
  search: URLSearchParams,
  key: string,
  value: unknown
): void {
  if (value === undefined || value === null) return;
  if (Array.isArray(value)) {
    for (const item of value) appendFluxRouteQuery(search, key, item);
    return;
  }
  search.append(key, String(value));
}

export const routes = {
  hotelRooms: (input: {
  hotel_id: number;
  query: {
    minimumRate: string;
  };
}): string => {
    let path = "/hotels/{hotel_id}/rooms";
    path = path.replace("{hotel_id}", encodeURIComponent(String(input["hotel_id"])));
    const search = new URLSearchParams();
    appendFluxRouteQuery(search, "minimumRate", input.query?.["minimumRate"]);
    const query = search.toString();
    return query ? `${path}?${query}` : path;
  },
} as const;
