// AUTO-GENERATED BY FLUXFAST.
// DO NOT EDIT MANUALLY.
// Schema: fluxfast-schema/2
// Producer: 1.1.0
// Fingerprint: 541a688a1f3aff53317ebdb67b10aa808479b70529f7d706b5bc9b96a2069a77

import type {} from "@fluxfast/core";

export const resourceKeys = {
  rooms: "rooms",
} as const;

export interface CreateRoomInput {
  inputName: string;
}

export interface Room {
  id: number;
  nightlyRate: string;
}

export interface UpdateRoomBody {
  inputName: string;
}

export interface User {
  displayName: string;
  id: number;
}

export type RoomsResource = Room[];

export interface GeneratedFluxResourceMap {
  rooms: RoomsResource;
}

declare module "@fluxfast/core" {
  interface FluxResourceMap {
    rooms: RoomsResource;
  }
}
