// AUTO-GENERATED BY FLUXFAST.
// DO NOT EDIT MANUALLY.
// Schema: fluxfast-schema/2
// Producer: 1.1.0
// Fingerprint: 541a688a1f3aff53317ebdb67b10aa808479b70529f7d706b5bc9b96a2069a77

import { createValidator } from "@fluxfast/core";
import type { FluxValidator } from "@fluxfast/core";
import type {
  CreateRoomInput,
  UpdateRoomBody,
  User,
} from "./types.generated";

export const validatorDiagnostics = [
  {
    "contract": "RoomsResource",
    "path": "$.resources.rooms.schema.$defs.Room.properties.nightlyRate.pattern",
    "message": "[fluxfast] Could not compile schema at $.resources.rooms.schema.$defs.Room.properties.nightlyRate.pattern: pattern uses a regex escape whose semantics are not portable to the native validator",
    "keyword": "pattern"
  }
] as const;

export const CreateRoomInputValidator: FluxValidator<CreateRoomInput> = /* @__PURE__ */ createValidator<CreateRoomInput>(
{
    "root": {
      "kind": "object",
      "properties": {
        "inputName": {
          "kind": "string",
          "minLength": 2
        }
      },
      "required": [
        "inputName"
      ]
    }
  }
);

export const UpdateRoomBodyValidator: FluxValidator<UpdateRoomBody> = /* @__PURE__ */ createValidator<UpdateRoomBody>(
{
    "root": {
      "kind": "object",
      "properties": {
        "inputName": {
          "kind": "string",
          "minLength": 2
        }
      },
      "required": [
        "inputName"
      ]
    }
  }
);

export const UserValidator: FluxValidator<User> = /* @__PURE__ */ createValidator<User>(
{
    "root": {
      "kind": "object",
      "properties": {
        "displayName": {
          "kind": "string"
        },
        "id": {
          "kind": "integer"
        }
      },
      "required": [
        "displayName",
        "id"
      ]
    }
  }
);

export const validators = {
  CreateRoomInput: CreateRoomInputValidator,
  UpdateRoomBody: UpdateRoomBodyValidator,
  User: UserValidator,
} as const;
