// GENERATED BY FLUXFAST.
// Run `fluxfast init --force` to repair this file.

import { createFluxTransportHandler } from "@fluxfast/next/server";

export const dynamic = "force-dynamic";
const transport = createFluxTransportHandler();

export const GET = transport;
export const HEAD = transport;
export const POST = transport;
export const PUT = transport;
export const PATCH = transport;
export const DELETE = transport;
