import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import {
  generateFluxFastProject,
  generatePagesRegistry
} from "../src/generate";

const fingerprint = "e".repeat(64);

function schemaManifest(resources: Record<string, unknown> = {}): string {
  return `${JSON.stringify({
    schema: "fluxfast-schema/1",
    producer: "0.6.0",
    fingerprint,
    resources,
    pages: [],
    mutations: []
  })}\n`;
}

describe("Pages Registry Generator", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "fluxfast-gen-test-"));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("scans pages directory and outputs registry file", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    fs.mkdirSync(path.join(pagesDir, "(admin)"), { recursive: true });
    fs.mkdirSync(path.join(pagesDir, "dashboard"), { recursive: true });
    fs.mkdirSync(path.join(pagesDir, "rooms"), { recursive: true });

    fs.writeFileSync(path.join(pagesDir, "(admin)/[room-id].tsx"), "export default null");
    fs.writeFileSync(path.join(pagesDir, "dashboard/index.tsx"), "export default function Dashboard() {}");
    fs.writeFileSync(path.join(pagesDir, "rooms/index.tsx"), "export default function Rooms() {}");
    fs.writeFileSync(path.join(pagesDir, "rooms/index.test.tsx"), "export default null");
    fs.writeFileSync(path.join(pagesDir, "rooms/_private.tsx"), "export default null");

    const outputFile = path.join(tmpDir, "src/.fluxfast/pages.generated.ts");

    generatePagesRegistry({ pagesDir, outputFile });

    expect(fs.existsSync(outputFile)).toBe(true);
    const content = fs.readFileSync(outputFile, "utf-8");

    expect(content).toContain('"(admin)/[room-id]":');
    expect(content).toContain('"dashboard/index":');
    expect(content).toContain('"rooms/index":');
    expect(content).toContain("AUTO-GENERATED BY FLUXFAST");
    expect(content).toContain("load: () => import(");
    expect(content).toContain("FluxApplication");
    expect(content).not.toContain("index.test");
    expect(content).not.toContain("_private");
  });

  it("rejects page paths that are unsafe to emit into generated source", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    fs.mkdirSync(pagesDir, { recursive: true });
    fs.writeFileSync(
      path.join(pagesDir, 'rooms";globalThis.compromised=true;.tsx'),
      "export default function UnsafePage() {}"
    );
    const outputFile = path.join(tmpDir, "src/.fluxfast/pages.generated.ts");

    expect(() => generatePagesRegistry({ pagesDir, outputFile })).toThrow(
      /Page path contains unsupported characters/
    );
    expect(fs.existsSync(outputFile)).toBe(false);
  });

  it("rejects duplicate identifiers from TypeScript and JavaScript pages", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    fs.mkdirSync(path.join(pagesDir, "rooms"), { recursive: true });
    fs.writeFileSync(
      path.join(pagesDir, "rooms/index.tsx"),
      "export default function Rooms() {}"
    );
    fs.writeFileSync(
      path.join(pagesDir, "rooms/index.jsx"),
      "export default function DuplicateRooms() {}"
    );
    const outputFile = path.join(tmpDir, "src/.fluxfast/pages.generated.ts");

    expect(() => generatePagesRegistry({ pagesDir, outputFile })).toThrow(
      /Duplicate FluxFast page identifier/
    );
    expect(fs.existsSync(outputFile)).toBe(false);
  });

  it("rejects project artifacts outside the configured output directory before writing", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const generatedDir = path.join(tmpDir, "src/.fluxfast");
    const escapedRegistry = path.join(tmpDir, "escaped-registry.ts");

    expect(() =>
      generateFluxFastProject({
        pagesDir,
        generatedDir,
        outputFile: escapedRegistry,
        log: false
      })
    ).toThrow(/component registry must stay inside the configured output directory/);
    expect(fs.existsSync(escapedRegistry)).toBe(false);
    expect(fs.existsSync(generatedDir)).toBe(false);

    const escapedSchema = path.join(tmpDir, "escaped-schema.json");
    expect(() =>
      generateFluxFastProject({
        pagesDir,
        generatedDir,
        outputFile: path.join(generatedDir, "pages.generated.ts"),
        schemaFile: escapedSchema,
        schemaContent: schemaManifest(),
        log: false
      })
    ).toThrow(/schema manifest must stay inside the configured output directory/);
    expect(fs.existsSync(escapedSchema)).toBe(false);
    expect(fs.existsSync(generatedDir)).toBe(false);
  });

  it("refuses to follow generated-file symbolic links", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const generatedDir = path.join(tmpDir, "src/.fluxfast");
    const outputFile = path.join(generatedDir, "pages.generated.ts");
    const outsideFile = path.join(tmpDir, "outside.ts");
    fs.mkdirSync(generatedDir, { recursive: true });
    fs.writeFileSync(outsideFile, "leave me alone", "utf8");
    fs.symlinkSync(outsideFile, outputFile);

    expect(() =>
      generateFluxFastProject({
        pagesDir,
        generatedDir,
        outputFile,
        log: false
      })
    ).toThrow(/component registry must not traverse the symbolic link/);
    expect(fs.readFileSync(outsideFile, "utf8")).toBe("leave me alone");
  });

  it("refuses page-only and schema generation through a symlinked output directory", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const generatedDir = path.join(tmpDir, "src/.fluxfast");
    const outside = fs.mkdtempSync(path.join(os.tmpdir(), "fluxfast-output-test-"));
    fs.mkdirSync(path.dirname(generatedDir), { recursive: true });
    fs.symlinkSync(outside, generatedDir, "dir");

    try {
      expect(() => generatePagesRegistry({
        pagesDir,
        outputFile: path.join(generatedDir, "pages.generated.ts"),
        log: false
      })).toThrow(/must not traverse the symbolic link/);
      expect(fs.readdirSync(outside)).toEqual([]);

      expect(() => generateFluxFastProject({
        pagesDir,
        generatedDir,
        outputFile: path.join(generatedDir, "pages.generated.ts"),
        schemaContent: schemaManifest(),
        log: false
      })).toThrow(/must not traverse the symbolic link/);
      expect(fs.readdirSync(outside)).toEqual([]);
    } finally {
      fs.rmSync(outside, { recursive: true, force: true });
    }
  });

  it("refuses an intermediate symlink in a nested output directory", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const outside = fs.mkdtempSync(path.join(os.tmpdir(), "fluxfast-nested-output-test-"));
    const redirected = path.join(tmpDir, "src/redirected");
    const generatedDir = path.join(redirected, "nested/.fluxfast");
    fs.mkdirSync(path.dirname(redirected), { recursive: true });
    fs.symlinkSync(outside, redirected, "dir");

    try {
      expect(() => generateFluxFastProject({
        pagesDir,
        generatedDir,
        outputFile: path.join(generatedDir, "pages.generated.ts"),
        schemaContent: schemaManifest(),
        log: false
      })).toThrow(/must not traverse the symbolic link/);
      expect(fs.readdirSync(outside)).toEqual([]);
    } finally {
      fs.rmSync(outside, { recursive: true, force: true });
    }
  });

  it.each([
    "schema.generated.json",
    "pages.generated.ts",
    "types.generated.ts",
    "validators.generated.ts",
    "routes.generated.ts",
    "mutations.generated.ts"
  ])("keeps every generated artifact unchanged when %s is a symlink", unsafeName => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const generatedDir = path.join(tmpDir, "src/.fluxfast");
    const outside = fs.mkdtempSync(path.join(os.tmpdir(), "fluxfast-artifact-test-"));
    const names = [
      "schema.generated.json",
      "pages.generated.ts",
      "types.generated.ts",
      "validators.generated.ts",
      "routes.generated.ts",
      "mutations.generated.ts"
    ];
    fs.mkdirSync(generatedDir, { recursive: true });
    for (const name of names) {
      fs.writeFileSync(path.join(generatedDir, name), `original:${name}`, "utf8");
    }
    const outsideFile = path.join(outside, unsafeName);
    fs.writeFileSync(outsideFile, `outside:${unsafeName}`, "utf8");
    fs.unlinkSync(path.join(generatedDir, unsafeName));
    fs.symlinkSync(outsideFile, path.join(generatedDir, unsafeName));

    try {
      expect(() => generateFluxFastProject({
        pagesDir,
        generatedDir,
        outputFile: path.join(generatedDir, "pages.generated.ts"),
        schemaFile: path.join(generatedDir, "schema.generated.json"),
        schemaContent: schemaManifest(),
        log: false
      })).toThrow(/must not traverse the symbolic link/);
      for (const name of names) {
        const expected = name === unsafeName
          ? `outside:${unsafeName}`
          : `original:${name}`;
        expect(fs.readFileSync(path.join(generatedDir, name), "utf8")).toBe(expected);
      }
      expect(fs.readFileSync(outsideFile, "utf8")).toBe(`outside:${unsafeName}`);
    } finally {
      fs.rmSync(outside, { recursive: true, force: true });
    }
  });

  it("rejects an oversized manifest without changing generated files", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const generatedDir = path.join(tmpDir, "src/.fluxfast");
    const outputFile = path.join(generatedDir, "pages.generated.ts");
    fs.mkdirSync(generatedDir, { recursive: true });
    fs.writeFileSync(outputFile, "existing registry", "utf8");

    expect(() => generateFluxFastProject({
      pagesDir,
      generatedDir,
      outputFile,
      schemaContent: " ".repeat(8 * 1024 * 1024 + 1),
      log: false
    })).toThrow(/source must not exceed 8388608 characters/);
    expect(fs.readdirSync(generatedDir)).toEqual(["pages.generated.ts"]);
    expect(fs.readFileSync(outputFile, "utf8")).toBe("existing registry");
  });

  it("keeps hostile resource and model names inside fixed generated files", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const generatedDir = path.join(tmpDir, "src/.fluxfast");
    const outputFile = path.join(generatedDir, "pages.generated.ts");
    const resourceKey = "../../malicious.ts";
    const modelTitle = '../../model";globalThis.compromised=true;.ts';

    const result = generateFluxFastProject({
      pagesDir,
      generatedDir,
      outputFile,
      schemaContent: schemaManifest({
        [resourceKey]: {
          schema: {
            title: modelTitle,
            type: "object",
            properties: {
              '../../field";globalThis.compromised=true': { type: "string" }
            }
          }
        }
      }),
      log: false
    });

    expect(result.generatedFiles.sort()).toEqual([
      path.join(generatedDir, "mutations.generated.ts"),
      path.join(generatedDir, "pages.generated.ts"),
      path.join(generatedDir, "routes.generated.ts"),
      path.join(generatedDir, "types.generated.ts"),
      path.join(generatedDir, "validators.generated.ts")
    ]);
    expect(fs.readdirSync(generatedDir).sort()).toEqual([
      "mutations.generated.ts",
      "pages.generated.ts",
      "routes.generated.ts",
      "schema.generated.json",
      "types.generated.ts",
      "validators.generated.ts"
    ]);
    expect(fs.existsSync(path.join(tmpDir, "malicious.ts"))).toBe(false);
    expect(fs.existsSync(path.join(tmpDir, "model.ts"))).toBe(false);
  });

  it("keeps schema/1 TypeScript generation available for unsupported validators", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    const generatedDir = path.join(tmpDir, "src/.fluxfast");
    const outputFile = path.join(generatedDir, "pages.generated.ts");

    const result = generateFluxFastProject({
      pagesDir,
      generatedDir,
      outputFile,
      schemaContent: schemaManifest({
        tags: {
          schema: {
            type: "array",
            items: { type: "string" },
            uniqueItems: true
          }
        },
        users: {
          schema: {
            type: "array",
            items: { type: "string" }
          }
        }
      }),
      log: false
    });

    const types = fs.readFileSync(
      path.join(generatedDir, "types.generated.ts"),
      "utf8"
    );
    const validators = fs.readFileSync(
      path.join(generatedDir, "validators.generated.ts"),
      "utf8"
    );
    expect(types).toContain("TagsResource");
    expect(types).toContain("UsersResource");
    expect(validators).toContain("UsersResourceValidator");
    expect(validators).not.toContain("TagsResourceValidator");
    expect(validators).toContain('"uniqueItems"');
    expect(result.generatedValidators).toEqual(["UsersResource"]);
    expect(result.validatorDiagnostics).toEqual([
      expect.objectContaining({
        contract: "TagsResource",
        keyword: "uniqueItems"
      })
    ]);
  });
});
