import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { generatePagesRegistry } from "../src/generate";

describe("Pages Registry Generator", () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "fluxfast-gen-test-"));
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("scans pages directory and outputs registry file", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    fs.mkdirSync(path.join(pagesDir, "(admin)"), { recursive: true });
    fs.mkdirSync(path.join(pagesDir, "dashboard"), { recursive: true });
    fs.mkdirSync(path.join(pagesDir, "rooms"), { recursive: true });

    fs.writeFileSync(path.join(pagesDir, "(admin)/[room-id].tsx"), "export default null");
    fs.writeFileSync(path.join(pagesDir, "dashboard/index.tsx"), "export default function Dashboard() {}");
    fs.writeFileSync(path.join(pagesDir, "rooms/index.tsx"), "export default function Rooms() {}");
    fs.writeFileSync(path.join(pagesDir, "rooms/index.test.tsx"), "export default null");
    fs.writeFileSync(path.join(pagesDir, "rooms/_private.tsx"), "export default null");

    const outputFile = path.join(tmpDir, "src/.fluxfast/pages.generated.ts");

    generatePagesRegistry({ pagesDir, outputFile });

    expect(fs.existsSync(outputFile)).toBe(true);
    const content = fs.readFileSync(outputFile, "utf-8");

    expect(content).toContain('"(admin)/[room-id]":');
    expect(content).toContain('"dashboard/index":');
    expect(content).toContain('"rooms/index":');
    expect(content).toContain("AUTO-GENERATED BY FLUXFAST");
    expect(content).toContain("load: () => import(");
    expect(content).toContain("FluxApplication");
    expect(content).not.toContain("index.test");
    expect(content).not.toContain("_private");
  });

  it("rejects page paths that are unsafe to emit into generated source", () => {
    const pagesDir = path.join(tmpDir, "src/flux-pages");
    fs.mkdirSync(pagesDir, { recursive: true });
    fs.writeFileSync(
      path.join(pagesDir, 'rooms";globalThis.compromised=true;.tsx'),
      "export default function UnsafePage() {}"
    );
    const outputFile = path.join(tmpDir, "src/.fluxfast/pages.generated.ts");

    expect(() => generatePagesRegistry({ pagesDir, outputFile })).toThrow(
      /Page path contains unsupported characters/
    );
    expect(fs.existsSync(outputFile)).toBe(false);
  });
});
