import { describe, expect, it } from "vitest";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { compileFluxFastResourceTypes } from "../src/schema-compiler";

const fingerprint = "b".repeat(64);

function manifest(resources: Record<string, { schema: Record<string, unknown> }>) {
  return {
    schema: "fluxfast-schema/1",
    producer: "0.6.0",
    fingerprint,
    resources,
    pages: [],
    mutations: []
  };
}

function expectValidTypeScript(source: string): void {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "fluxfast-types-"));
  const sourceFile = path.join(directory, "types.generated.ts");
  fs.writeFileSync(sourceFile, source, "utf8");
  try {
    const result = spawnSync(
      path.resolve(__dirname, "../node_modules/typescript/bin/tsc"),
      [
        "--noEmit",
        "--ignoreConfig",
        "--target",
        "ES2022",
        "--module",
        "Node16",
        "--moduleResolution",
        "Node16",
        "--skipLibCheck",
        sourceFile
      ],
      { encoding: "utf8" }
    );
    expect(`${result.stdout}${result.stderr}`).toBe("");
    expect(result.status).toBe(0);
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
}

describe("FluxFast JSON Schema compiler", () => {
  it("generates readable model, enum, array, optional, and formatted string types", () => {
    const output = compileFluxFastResourceTypes(
      manifest({
        rooms: {
          schema: {
            $defs: {
              Room: {
                title: "Room",
                type: "object",
                properties: {
                  createdAt: { type: "string", format: "date-time" },
                  id: { type: "integer" },
                  label: { type: "string" },
                  status: { $ref: "#/$defs/RoomStatus" }
                },
                required: ["id", "status"]
              },
              RoomStatus: {
                title: "RoomStatus",
                enum: ["available", "occupied"],
                type: "string"
              }
            },
            type: "array",
            items: { $ref: "#/$defs/Room" }
          }
        }
      })
    );

    expect(output).toBe(`// AUTO-GENERATED BY FLUXFAST.
// DO NOT EDIT MANUALLY.
// Schema: fluxfast-schema/1
// Producer: 0.6.0
// Fingerprint: ${fingerprint}

export interface Room {
  createdAt?: string;
  id: number;
  label?: string;
  status: RoomStatus;
}

export type RoomStatus = "available" | "occupied";

export type RoomsResource = Room[];
`);
    expectValidTypeScript(output);
  });

  it("supports records, unions, nullable values, constants, and unconstrained schemas", () => {
    const output = compileFluxFastResourceTypes(
      manifest({
        settings: {
          schema: {
            title: "Settings",
            type: "object",
            properties: {
              mode: { const: "safe" },
              note: { anyOf: [{ type: "string" }, { type: "null" }] },
              payload: {},
              value: { oneOf: [{ type: "number" }, { type: "boolean" }] }
            },
            required: ["mode", "note", "payload", "value"]
          }
        },
        totals: {
          schema: {
            type: "object",
            additionalProperties: { type: "number" }
          }
        }
      })
    );

    expect(output).toContain("export interface Settings {");
    expect(output).toContain('mode: "safe";');
    expect(output).toContain("note: string | null;");
    expect(output).toContain("payload: unknown;");
    expect(output).toContain("value: number | boolean;");
    expect(output).toContain("export type SettingsResource = Settings;");
    expect(output).toContain(
      "export type TotalsResource = { [key: string]: number; };"
    );
    expect(output).not.toContain("any");
  });

  it("supports nested, recursive, and allOf references", () => {
    const output = compileFluxFastResourceTypes(
      manifest({
        trees: {
          schema: {
            $defs: {
              BaseNode: {
                title: "BaseNode",
                type: "object",
                properties: { id: { type: "string" } },
                required: ["id"]
              },
              Node: {
                title: "Node",
                allOf: [
                  { $ref: "#/$defs/BaseNode" },
                  {
                    type: "object",
                    properties: {
                      children: {
                        type: "array",
                        items: { $ref: "#/$defs/Node" }
                      }
                    },
                    required: ["children"]
                  }
                ]
              }
            },
            type: "array",
            items: { $ref: "#/$defs/Node" }
          }
        }
      })
    );

    expect(output).toContain("export interface BaseNode");
    expect(output).toContain(
      "export type Node = BaseNode & { children: Node[]; };"
    );
    expect(output).toContain("export type TreesResource = Node[];");
  });

  it("quotes unsafe property names and rejects unresolved or external references", () => {
    const output = compileFluxFastResourceTypes(
      manifest({
        values: {
          schema: {
            title: "Payload",
            type: "object",
            properties: {
              'value"; globalThis.compromised = true; "': { type: "string" }
            }
          }
        }
      })
    );
    expect(output).toContain(
      '"value\\\"; globalThis.compromised = true; \\\""?: string;'
    );

    expect(() =>
      compileFluxFastResourceTypes(
        manifest({ broken: { schema: { $ref: "#/$defs/Missing" } } })
      )
    ).toThrow(/references unknown definition "Missing"/);
    expect(() =>
      compileFluxFastResourceTypes(
        manifest({ broken: { schema: { $ref: "https:\/\/example.com/schema" } } })
      )
    ).toThrow(/only local \$defs references are supported/);
  });

  it("is deterministic and rejects normalized resource and model collisions", () => {
    const input = manifest({
      beta: { schema: { type: "boolean" } },
      alpha: { schema: { type: "string" } }
    });
    expect(compileFluxFastResourceTypes(input)).toBe(
      compileFluxFastResourceTypes(input)
    );
    expect(compileFluxFastResourceTypes(input)).toContain(
      "export type AlphaResource = string;\n\nexport type BetaResource = boolean;"
    );

    expect(() =>
      compileFluxFastResourceTypes(
        manifest({
          "room-types": { schema: { type: "string" } },
          room_types: { schema: { type: "number" } }
        })
      )
    ).toThrow(/collides .* as TypeScript name RoomTypesResource/);

    expect(() =>
      compileFluxFastResourceTypes(
        manifest({
          first: {
            schema: {
              $defs: {
                "room-type": { title: "RoomType", type: "string" },
                room_type: { title: "RoomType", type: "number" }
              },
              type: "string"
            }
          }
        })
      )
    ).toThrow(/model name RoomType collides with an incompatible definition/);
  });
});
