import assert from "node:assert/strict";
import test from "node:test";
import { comparableTypedArtifact } from "./types-consumer-comparison.mjs";

const schema = producer => Buffer.from(JSON.stringify({ schema: "fluxfast-schema/2", producer,
  fingerprint: "a".repeat(64), resources: [{ key: "items", schema: { type: "array" } }] }, null, 2) + "\n");
const typed = producer => Buffer.from(`// AUTO-GENERATED BY FLUXFAST.\n// Producer: ${producer}\n// Fingerprint: ${"a".repeat(64)}\nexport type Item = { id: number };\n`);

test("mixed producer versions change metadata, not generated contract bytes", () => {
  assert.deepEqual(comparableTypedArtifact("schema.generated.json", schema("1.2.0"), "1.2.0"),
    comparableTypedArtifact("schema.generated.json", schema("1.1.0"), "1.1.0"));
  const compact = producer => Buffer.from(JSON.stringify({ fingerprint: "a".repeat(64), producer,
    resources: { nested: { producer: "application-owned", description: 'braces {} and "producer": "1.2.0"' } } }) + "\n");
  assert.deepEqual(comparableTypedArtifact("schema.generated.json", compact("1.2.0"), "1.2.0"),
    comparableTypedArtifact("schema.generated.json", compact("1.1.0"), "1.1.0"));
  assert.match(comparableTypedArtifact("schema.generated.json", compact("1.2.0"), "1.2.0").toString(), /"producer":"application-owned"/);
  for (const name of ["types.generated.ts", "validators.generated.ts", "routes.generated.ts", "mutations.generated.ts"]) {
    assert.deepEqual(comparableTypedArtifact(name, typed("1.2.0"), "1.2.0"),
      comparableTypedArtifact(name, typed("1.1.0"), "1.1.0"));
  }
  const registry = Buffer.from('export const versionLabel = "1.2.0";\n');
  assert.equal(comparableTypedArtifact("pages.generated.ts", registry, "1.2.0"), registry);
});

test("producer normalization does not hide fingerprint, contract, formatting, or application drift", () => {
  for (const changed of [schema("1.2.0").toString().replace("a".repeat(64), "b".repeat(64)),
    schema("1.2.0").toString().replace('"items"', '"other"'),
    schema("1.2.0").toString().replace('"array"', '"object"'),
    schema("1.2.0").toString().replace('"schema":', '"schema" :')]) {
    assert.notDeepEqual(comparableTypedArtifact("schema.generated.json", Buffer.from(changed), "1.2.0"),
      comparableTypedArtifact("schema.generated.json", schema("1.1.0"), "1.1.0"));
  }
  const baseline = comparableTypedArtifact("types.generated.ts", typed("1.1.0"), "1.1.0");
  for (const changed of [typed("1.2.0").toString().replace("number", "string"),
    typed("1.2.0").toString().replace("a".repeat(64), "b".repeat(64)),
    typed("1.2.0").toString() + '// Application producer: 1.2.0\n']) {
    assert.notDeepEqual(comparableTypedArtifact("types.generated.ts", Buffer.from(changed), "1.2.0"), baseline);
  }
});

test("comparison rejects false, missing, duplicate, and malformed producer metadata", () => {
  for (const name of ["schema.generated.json", "types.generated.ts"]) {
    const bytes = name.endsWith("json") ? schema("1.1.0") : typed("1.1.0");
    assert.throws(() => comparableTypedArtifact(name, bytes, "1.2.0"), /producer/i);
  }
  for (const source of ['// Producer: 1.2.0\n// Producer: 1.2.0\n', '// Producer: 1.2.0-extra\n', 'export type Item = string;\n']) {
    assert.throws(() => comparableTypedArtifact("types.generated.ts", Buffer.from(source), "1.2.0"), /producer/i);
  }
  assert.throws(() => comparableTypedArtifact("schema.generated.json", Buffer.from('{"producer":"1.2.0","producer":"1.2.0"}'), "1.2.0"), /top-level/);
  assert.throws(() => comparableTypedArtifact("unexpected.ts", Buffer.from(""), "1.2.0"), /unexpected/);
  assert.throws(() => comparableTypedArtifact("pages.generated.ts", Buffer.from(""), "1.2.0-rc.1"));
});
