// GENERATED BY FLUXFAST.
// Run `fluxfast init --force` to repair this file.

import { createFluxHealthHandler } from "@fluxfast/next/server";

export const dynamic = "force-dynamic";
export const GET = createFluxHealthHandler();
